### ISSUE TITLE
可以设置精确的录音长度吗？

### ISSUE THREAD

**Issue by x8edu** [xiangyuecn/Recorder#10]
例如要求录音10秒，用setTimeout出来的可能是10.1 或 9.9秒，能精确到毫秒数吗？

**Comment by xiangyuecn** [comment]
有些格式可以做到很精确，好像有些不可以，跟底层的编码器有关系（好像有些会丢弃末尾未达到一个block的数据，研究源码时候瞄到的，未证实）。对于可以精确的，我们可以这样做（意义不大，人又不是机器能判断到这么精准，也许会有牛逼的产品经理提这种需求，把抽屉里的菜刀拿出来 :knife: :trollface:）

## 方法1
直接修改数据源。在调用stop之前，裁剪this.buffer中的数据，达到刚好10秒，要保留的数据长度=this.srcSampleRate*10。操作buffer这个2维数组好像有点复杂，不过这个办法最简单。

## 方法2

自己实现一个假的格式，然后使用mock生成实际格式：
``` javascript
Recorder.prototype.xxx=function(res,True,False){
    res=res.subarray(0,this.set.sampleRate*10);
    this.set.type="mp3"//实际需要的类型
    Recorder(this.set).mock(res,this.set.sampleRate).stop(function(blob,time){
       timeX=time;
        True(blob);
    },False);
}

//测试录13秒返回10秒
var timeX;//mock后时间是原始源的时间
var res=Recorder({type:"xxx"});
res.open(function(){
    console.log("录制中，等待13秒")
    res.start();
   setTimeout(function(){res.stop(function(o,t){console.log(o,timeX)})},13000);
});
```
## 最后
大概就是这样操作，当然录音时间没达到还要额外处理:smile:
