### ISSUE TITLE
Bitrate设置256时，生成文件变为160

### ISSUE THREAD

**Issue by CACppuccino** [xiangyuecn/Recorder#101]
你好，

我们的业务需要用到单声道16bit, sampleRate=16k的，所以bitrate要求是256 。
我们在自己的demo和github提供的DEMO上都做了测试，发现生成的文件中，bitrate都自动从256降为了160，请问这是为何？

感谢

**Comment by xiangyuecn** [comment]
wav？wav比特率是 位数*采样率/1000，你16位16k的=16*16=256，另外8*16=128，160是怎么得出来的？

**Comment by CACppuccino** [comment]
> wav？wav比特率是 位数 * 采样率/1000，你16位16k的=16 * 16=256，另外8 * 16=128，160是怎么得出来的？
> 
> > 星号被吃了😂

是mp3，公式按照 BitRate = 通道数（1） \* 采样率(16k) \* 位数(16) = 256 kbps ， 

160是在您提供的[在线代码Demo](https://xiangyuecn.github.io/Recorder/assets/%E5%B7%A5%E5%85%B7-%E4%BB%A3%E7%A0%81%E8%BF%90%E8%A1%8C%E5%92%8C%E9%9D%99%E6%80%81%E5%88%86%E5%8F%91Runtime.html?idf=self_base_demo)中，把bitrate改完256后，输出的结果是
> 已录制:160kbps 16000hz 95760b [mp3]04″776ms

**Comment by xiangyuecn** [comment]
mp3没有位数的概念，你那个16位就是16kbps的比特率，不同的采样率能支持的比特率是不同的，同样，不同比特率支持的采用率范围是不同的。这个是mp3格式里面的一个固定规范。

所以最后mp3编码结果，你给了一个16khz不支持的比特率256，mp3编码器会自动调整成合法的比特率160

**Comment by xiangyuecn** [comment]
采样率改成 32khz以上就能支持 256kbps比特率了
