### ISSUE TITLE
小米浏览器无法录音

### ISSUE THREAD

**Issue by lgst** [xiangyuecn/Recorder#102]
报错：NotReadableError

**Comment by xiangyuecn** [comment]
别指望小米浏览器能录

**Comment by xiangyuecn** [comment]
很早以前的版本能录，后面加了小视频这些垃圾货色，目测是阉割掉了10M多的webrtc功能来放小视频功能

**Comment by lgst** [comment]
好吧，辣鸡小米

**Comment by xiangyuecn** [comment]
国产浏览器都这路货色，没有哪个不放小视频的

**Comment by lgst** [comment]
Chrome可以，但是我用webview提示：NotReadableError

**Comment by lgst** [comment]
难道小米ROM的Chrome内核也不行？

**Comment by xiangyuecn** [comment]
app权限、网页权限 都要有，你这个是app没有录音权限

**Comment by lgst** [comment]
确实是少注册了一个权限，谢谢了
