### ISSUE TITLE
 ios微信浏览器使用RecoderApp 配置ios-weixin-config.js，请求错误

### ISSUE THREAD

**Issue by jiajia12** [xiangyuecn/Recorder#103]
ios微信浏览器使用RecoderApp 配置ios-weixin-config.js  修改本地api接口，使用xmlHttpRequest请求返回的状态xhr.status=0，一直请求错误是什么原因

**Comment by xiangyuecn** [comment]
换成你平时用的接口请求方式就行，只要得到服务器数据，调用sucess把数据进行回调就能正常使用

**Comment by jiajia12** [comment]
> 换成你平时用的接口请求方式就行，只要得到服务器数据，调用sucess把数据进行回调就能正常使用
谢谢，解决了， 是后台接口配置的问题
