### ISSUE TITLE
求助，输出mp3格式，设置bitRate为128出现明显杂音

### ISSUE THREAD

**Issue by THROFHR** [xiangyuecn/Recorder#104]
根据官方 QuickStart.html，修改了输出音频格式，录音有很明显杂音
这里可以[在线预览地址](https://tp-image.vercel.app/record.html)，比对16kbps和128kbps的区别（ps：切换比特率后需先要关闭录音，释放资源）
```
var newRec=Recorder({
		type:"mp3",sampleRate:44100,bitRate:128 //mp3格式，指定采样率hz、比特率kbps，其他参数使用默认配置；注意：是数字的参数必须提供数字，不要用字符串；需要使用的type类型，需提前把格式支持文件加载进来，比如使用wav格式需要提前加载wav.js编码引擎
		,onProcess:function(buffers,powerLevel,bufferDuration,bufferSampleRate,newBufferIdx,asyncEnd){
			//录音实时回调，大约1秒调用12次本回调
			document.querySelector(".recpowerx").style.width=powerLevel+"%";
			document.querySelector(".recpowert").innerText=bufferDuration+" / "+powerLevel;
			
			//可视化图形绘制
			wave.input(buffers[buffers.length-1],powerLevel,bufferSampleRate);
		}
	});
```
需求是mp3格式需要比特率>=128kbps
请问是否有啥解决方案？

**Comment by xiangyuecn** [comment]
嗯应该是采样率抽样的问题，用16khz(天然切掉了高频杂音) 或者 48khz（原声），就没有杂音了，其他的采样率可能因为采样率转换的原因引入的高频杂音

**Comment by xiangyuecn** [comment]
Recorder H5测试demo里面可以方便的进行测试，因为里面有一个批量编码功能，比较好测试

https://xiangyuecn.gitee.io/recorder/

**Comment by THROFHR** [comment]
> 嗯应该是采样率抽样的问题，用16khz(天然切掉了高频杂音) 或者 48khz（原声），就没有杂音了，其他的采样率可能因为采样率转换的原因引入的高频杂音

没有处理音频这一块的经验，作者大大，有没有啥解决方案、思路？

**Comment by THROFHR** [comment]
> > 嗯应该是采样率抽样的问题，用16khz(天然切掉了高频杂音) 或者 48khz（原声），就没有杂音了，其他的采样率可能因为采样率转换的原因引入的高频杂音
> 
> 没有处理音频这一块的经验，作者大大，有没有啥解决方案、思路？

汗，没细看，我试试改为48khz的看看

**Comment by xiangyuecn** [comment]
采样率转换导致的杂音问题已修复

https://github.com/xiangyuecn/Recorder/commit/2a0f9a860cf0fc02f14c6b371f4b3c9794c975b5
