### ISSUE TITLE
从微信服务器上下载下来的amr文件是杂音

### ISSUE THREAD

**Issue by emcvhkr** [xiangyuecn/Recorder#106]
您好，我在使用 JSSDK 录音后从微信服务器上下载下来的 am r音频都是咕噜咕噜的杂音，是还需要配置一些额外选项吗

**Comment by emcvhkr** [comment]
您的在线测试页面录音后播放的内容是正常的，但是我自己写的有这个问题，后台服务器从微信获取的录音数据存成 amr 文件播放就全是咕噜咕噜的声音

**Comment by xiangyuecn** [comment]
😂 这个就不清楚了，微信的素材下载得到的二进制直接保存就是正常的amr，除非你哪里进行了转换

**Comment by emcvhkr** [comment]
哎呀，您这一说我查了下后台请求完确实做了默认转码，感谢提醒！
