### ISSUE TITLE
ios 使用git上ios demo，vue使用自个编写程序的 如下图所示，在手机自带的浏览器上测试都是可以使用；但把demo中的ios demo换成自个的，然后点击权限获取，就提示“打开失败：此浏览器不支持录音”。如果url换成git上ios demo的地址就能正常，谁知道这是为什么？

### ISSUE THREAD

**Issue by zjws23786** [xiangyuecn/Recorder#108]
![image](https://user-images.githubusercontent.com/22523707/100095778-fd52d100-2e95-11eb-8380-2041e147049f.png)
使用https://xiangyuecn.gitee.io/recorder/app-support-sample/能正常使用
换成自个的https://cdn.3maxbox.com/test/#/点击获取"请求权限"就报“打开失败：此浏览器不支持录音”

**Comment by xiangyuecn** [comment]
电脑上正常使用，Safari里内也应该也是正常使用的，除非你用的ios微信里面打开的。

app-support-sample 这个地址是 RecordApp 的测试，RecordApp对ios 微信做了兼容处理。

你集成的Recorder 在IOS里面只能在Safari里面用

**Comment by xiangyuecn** [comment]
RecordApp 没有提供 vue的demo，我那个vue demo是Recorder的😂

**Comment by zjws23786** [comment]
大神，目前有没针对RecordApp 给出vue demo的方案。

**Comment by xiangyuecn** [comment]
没有计划哦，照着文档写很容易的

**Comment by zjws23786** [comment]
这个是用Vue写的https://cdn.3maxbox.com/test/#/案例，把app-support-sample中demo_ios的地址替换掉，点击"权限获取"，就提示“打开失败：此浏览器不支持录音”。大神帮忙指导一下

**Comment by xiangyuecn** [comment]
嗯，你现在集成的是Recorder，Android app是正常的，ios app里面是不支持H5录音的。

你用RecordApp去录音就ok了，阅读 https://github.com/xiangyuecn/Recorder/tree/master/app-support-sample 这个文档中的 `方式二：通过import/require引入`，复制一下 native-config.js 文件到你自己的目录里面引入，然后用RecordApp的录音方法即可

**Comment by xiangyuecn** [comment]
你直接复制下面这个静态html文件到你的项目里面，只要这个html文件就ok，什么也不用改，也不用编译，应该ios app里面就能正常录音，方便测试

https://github.com/xiangyuecn/Recorder/blob/master/app-support-sample/QuickStart.html

**Comment by xiangyuecn** [comment]
已经有了一个 RecordApp的vue demo  https://github.com/xiangyuecn/Recorder/tree/master/assets/demo-vue

**Comment by zjws23786** [comment]
感谢大神，学习了
