### ISSUE TITLE
回声降噪的话要怎么加

### ISSUE THREAD

**Issue by WilliamALiang** [xiangyuecn/Recorder#109]
实现音频通话的时候，扬声器的声音就会出现回声死循环。看了一下像这种的降噪方面得加回声抑制，不知道这块有没有

**Comment by xiangyuecn** [comment]
浏览器给的就是已经默认降噪和抑制了回声的，如果还是很严重，似乎没有啥好办法，戴耳机吧😂

**Comment by WilliamALiang** [comment]
现在试了试外放的声音，自己说的还能听到

**Comment by xiangyuecn** [comment]
新版本set里面支持传递getUserMedia的audio参数set.audioTrackSet，回声可以尝试调节echoCancellation，降噪可调节noiseSuppression，但这些参数不一定会生效

https://github.com/xiangyuecn/Recorder/blob/ddd980e8e70715658519eee8d2fc8417b6fbca0c/README.md#L439-L442
