### ISSUE TITLE
微信jssdk上传录音后，服务端怎么下载？

### ISSUE THREAD

**Issue by mingtianyihou33** [xiangyuecn/Recorder#111]
调用https://api.weixin.qq.com/cgi-bin/media/get，会提示“40007 不合法的媒体文件 id”
但是https://api.weixin.qq.com/cgi-bin/media/get/jssdk 会提示“48001 api 功能未授权，请确认公众号已获得该接口”
您在recordApp中是用的服务号吗？

**Comment by xiangyuecn** [comment]
检查服务器端向微信服务器发起的请求参数

**Comment by mingtianyihou33** [comment]
是不是因为公众号没有认证导致的，我这是个人号。

**Comment by xiangyuecn** [comment]
应该没有关系，微信后台有一个权限列表 这种录音权限应该都是有的 不需要认证

**Comment by mingtianyihou33** [comment]
问题已解决，是使用了网页开发工具上传的语音，返回的serviceId是有问题的。用手机试了，是没问题的，两个接口地址都正常返回了。
