### ISSUE TITLE
ios微信端打开，出现音频可视化图形绘制失败的情况

### ISSUE THREAD

**Issue by ljhtx** [xiangyuecn/Recorder#114]
想问一下，是不是ios微信本身就不支持音频可视化呢？
![image](https://user-images.githubusercontent.com/47860962/104299257-f5132b80-54ff-11eb-855e-e00afb1f821d.png)
![image](https://user-images.githubusercontent.com/47860962/104298962-92219480-54ff-11eb-9330-72bd01ae4748.png)

**Comment by ljhtx** [comment]
好像网不太行，不知道作者大大看不看得到我上传的图，我把UA及相关信息贴一下：
IsWx:true
IsApp:false
Platforms:IOS-Weixin

AudioContext:false
webkitAudioContext:true
mediaDevices:false
mediaDevices.getUserMedia:false
navigator.getUserMedia:false
navigator.webkitGetUserMedia:false

URL:https://jiebian.life/web/h5/github/recordapp.aspx
UA:Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/7.0.18(0x17001233) NetType/4G Language/zh_CN

**Comment by xiangyuecn** [comment]
IOS-Weixin 底层用的微信的jssdk录音，没有任何回调，因此不会有可视化显示

**Comment by ljhtx** [comment]
感谢！
