### ISSUE TITLE
点击录音会发起一个请求

### ISSUE THREAD

**Issue by varmtone** [xiangyuecn/Recorder#115]
请求：http://ia.51.la/go1?id=20469973&pvFlag=1 
这是彩蛋吗？

**Comment by xiangyuecn** [comment]
【静态属性】Recorder.TrafficImgUrl
流量统计用1像素图片地址，在Recorder首次被实例化时将往这个地址发送一个请求，请求是通过Image对象来发送，安全可靠；默认开启统计，url为本库的51la统计用图片地址，为空响应流量消耗非常小，因此对使用几乎没有影响。

设置为空字符串后将不参与统计，大部分情况下无需关闭统计，如果你网页的url私密性要求很高，请在调用Recorder之前将此url设为空字符串；本功能于2019-11-09添加，点此前往51la查看统计概况。

**Comment by varmtone** [comment]
感谢
