### ISSUE TITLE
有没有办法能使takeoffEncodeChunk支持wav格式呢

### ISSUE THREAD

**Issue by ZYMoridae** [xiangyuecn/Recorder#116]

**Comment by xiangyuecn** [comment]
wav不需要takeoffEncodeChunk。takeoffEncodeChunk的存在完全是为了mp3，因为onProcess中mock实时转码mp3会有首尾静默（听起来会断断续续），所以通过takeoffEncodeChunk就能实时的拿到mp3的编码器输出，不存在首尾静默的问题。wav格式非常简单，就是pcm前面加了个wav头，就不存在mp3的这种问题了。

**Comment by ZYMoridae** [comment]
我还想问一下那个onProcess里面的buffers如何展开成一维的？有现成的工具函数吗

**Comment by ZYMoridae** [comment]
我在onProcess中使用mock方法进行编码，最后生成的声音也是断断续续的

**Comment by xiangyuecn** [comment]
wav不太可能断断续续，你试一下这个wav格式的实时转码看看：[【教程】实时转码并上传-通用版](https://xiangyuecn.gitee.io/recorder/assets/%E5%B7%A5%E5%85%B7-%E4%BB%A3%E7%A0%81%E8%BF%90%E8%A1%8C%E5%92%8C%E9%9D%99%E6%80%81%E5%88%86%E5%8F%91Runtime.html?jsname=teach.realtime.encode_transfer)

录完后，执行一下[【Demo库】【文件合并】-wav多个片段文件合并](https://xiangyuecn.gitee.io/recorder/assets/%E5%B7%A5%E5%85%B7-%E4%BB%A3%E7%A0%81%E8%BF%90%E8%A1%8C%E5%92%8C%E9%9D%99%E6%80%81%E5%88%86%E5%8F%91Runtime.html?jsname=lib.merge.wav_merge)，可以合并所有wav片段成一个文件来播放

**Comment by ZYMoridae** [comment]
我现在是想和另一个实时绘制波形的库连起来，我每次把buffers进行wav编码然后再使用blob传送给另外一个库绘图， 代码如下
`            this.currentBuffer = [...this.currentBuffer, ...buffers]
            
            chunkInfo = Recorder.SampleData(this.currentBuffer, sampleRate, 44100, chunkInfo);
            
            var recMock=Recorder({
              type:'wav'
              ,sampleRate:this.recordConfig.sampleRate //采样率
              ,bitRate:this.recordConfig.bitRate //比特率
            });
            recMock.mock(chunkInfo.data,chunkInfo.sampleRate);
            recMock.stop((blob,duration) => {
              this.drawWaveForm(blob)
            },function(msg){

            });`

每次都是前面几秒钟绘制的是对的而且声音没问题，过了三四秒以后波形就断断续续，声音也断断续续而且会速度也会变快

**Comment by xiangyuecn** [comment]
Recorder.SampleData 第一个参数直接放onProcess的buffers就ok了，不需要任何处理。你应该是第一行把数据搞乱了

**Comment by ZYMoridae** [comment]
我第一行是想把每次buffers拼接起来得到从录音开始到现在完整的pcm数据段，我试了一下你说的只传buffers，这样好像只得到了但前chunk的blob

**Comment by ZYMoridae** [comment]
还有就是我想问一下如果我使用mp3格式并且使用takeoffEncodeChunk函数能知道chunkBytes对应大概的时间长度吗？

**Comment by xiangyuecn** [comment]
`length*8/bitRate`

https://gitee.com/xiangyuecn/Recorder/blob/master/src/engine/mp3.js#L309
