### ISSUE TITLE
IOS配置：有关ios-weixin-config.js的配置

### ISSUE THREAD

**Issue by ljhtx** [xiangyuecn/Recorder#117]
作者晚上好，我看到ios-weixin-config.js中有这么一个配置：
window.RecordAppBaseFolder=window.PageSet_RecordAppBaseFolder||"https://xiangyuecn.gitee.io/recorder/src/";

但我的recordAPP是用npm安装的，并没有设置相应的文件夹，想了解一下，是否只需要
import 'recorder-core/src/app-support/app-ios-weixin-support'这一行代码，而我不需要再去ios-weixin-config.js中配置RecordAppBaseFolder呢？

期待您的回复，感谢！

**Comment by xiangyuecn** [comment]
不配置就要手动import所有文件，不然会从这个地址加载需要的js文件

https://github.com/xiangyuecn/Recorder/tree/master/app-support-sample 文档里面`通过import/require引入`有写需要import哪些文件

**Comment by ljhtx** [comment]
感谢！
