### ISSUE TITLE
点击多次“开始录音”导致录音覆盖的问题

### ISSUE THREAD

**Issue by ljhtx** [xiangyuecn/Recorder#118]
作者好，测试的时候，我发现在打开一个录音之后，再次去点击“开始”，会导致录音重新开始录制，因为业务需求，我需要提示一下用户会出现覆盖的情况，想问一下有无参数可以直接得知“**当前是否正在录音**“。

当然，我知道可以用计数的办法来做判断，主要想了解一下这个组件里头能否直接做判断，会较为方便一些。

期待您的回复。

**Comment by xiangyuecn** [comment]
这个跟界面交互逻辑关系比较大，自己开始录音的时候后给个变量就可以了（比如rec），结束或者其他情况就给清除掉这个变量。

第二次开始录音时判断一下有没有rec 有就弹提示，Recorder本身不带这种全局的状态

**Comment by ljhtx** [comment]
非常感谢！
