### ISSUE TITLE
IOS在微信使用js-sdk只能录音时间时间限制不能超过60S，超过60S音频不能正常播放

### ISSUE THREAD

**Issue by xiajingqi** [xiangyuecn/Recorder#119]
问题：IOS-Weixin使用的微信JsSDK单次调用录音最长为60秒，底层已屏蔽了这个限制，超时后会立即重启接续录音，因此当在IOS微信上录音时，超过60秒还未停止，将重启微信JsSDK录音，中间可能会导致短暂的停顿感觉。
实际测试结果：IOS在微信使用js-sdk只能录音时间时间限制不能超过60S，超过60S音频不能正常播放。

**Comment by xiangyuecn** [comment]
可以使用本库的在线demo对比测试一遍看看。

要是录制过程出现问题还算能理解，只要成功下载得到了amr数据，就和微信、苹果没有任何关系了，amr解码、转码mp3都是纯js操作。如果最终生成了mp3，并且这个mp3不能播放，这种可能性也是微乎其微的。

ps：完整的那个在线测试，录音完成后可以下载mp3数据，复制出base64数据，扔到电脑上base64解码成mp3方便分析
