### ISSUE TITLE
录音时长减少，播放倍速

### ISSUE THREAD

**Issue by cuiyunyun** [xiangyuecn/Recorder#120]
您好，有个问题需要请教大佬: 录了25s，暂停回显21s,播放的时候倍速，不好复现，可能录好几十次出现一次(windows、谷歌)
recorder-core/recorder.mp3.min

**Comment by cuiyunyun** [comment]
recorder-core/recorder.mp3.min

**Comment by xiangyuecn** [comment]
是不是设置了 disableEnvInFix ？ 如果是设置了这个参数为true，设备卡顿时，就会产生录音时长变短，因为卡的时候的音频数据丢失了，播放的时候就像快放一样

**Comment by cuiyunyun** [comment]
好的，谢谢
