### ISSUE TITLE
android webview 链接为什么还是有权限问题，按照hybrid app说明改的

### ISSUE THREAD

**Issue by bukebuchi** [xiangyuecn/Recorder#121]
webView.setWebChromeClient(new WebChromeClient() {
            @Override
            public void onPermissionRequest(final PermissionRequest request) {
                System.out.println("onPermissionRequest");
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                    request.grant(request.getResources());
                }
   }
<uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
增加了这几个地方的代码
但是还是没法获取权限呢？
cr_media: Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. Selected device will not be available for recording
想请问一下是不是只能用JSBRIGE来做

**Comment by xiangyuecn** [comment]
设置里面给app设置允许录音，一般都要套一层权限请求，请求到了app录音权限才request.grant
