### ISSUE TITLE
如果录音时间长，会导致this.buffer很大，在安卓webview里会越来越卡，有什么办法解决吗 

### ISSUE THREAD

**Issue by leifeng** [xiangyuecn/Recorder#133]

**Comment by xiangyuecn** [comment]
可以在onProcess里面清理掉buffers，数组内的元素全部设置为null，不过清理掉后不能stop (要stop得到结果，有点麻烦)

https://github.com/xiangyuecn/Recorder/blob/ddd980e8e70715658519eee8d2fc8417b6fbca0c/README.md#L503-L512

**Comment by leifeng** [comment]
我在`onProcess`里执行` buffers[newBufferIdx] = null;` 
在录音4分钟后也会有卡顿现象，在ios里不明显基本可以正常使用，但是在安卓里尝试使用x5内核与默认内核还是卡的厉害。

**Comment by leifeng** [comment]
安卓端把打日志功能去掉后就不卡了
