### ISSUE TITLE
onaudioprocess已经废弃了，为什么不用createAnalyser呢

### ISSUE THREAD

**Issue by awtmeng** [xiangyuecn/Recorder#142]
onaudioprocess已经废弃了，为什么不用createAnalyser呢？

**Comment by xiangyuecn** [comment]
createAnalyser对录音没什么卵用，目前用到的 createScriptProcessor 古董浏览器都支持， AudioWorklet 要新浏览器才支持，目前只使用createScriptProcessor就能完成所有浏览器的兼容

还没到要非要使用AudioWorklet的地步，这玩意ios里面要14.5+今年才开始支持 包括Safari
