### ISSUE TITLE
AudioContext支持设置采样率

### ISSUE THREAD

**Issue by awtmeng** [xiangyuecn/Recorder#143]
https://developer.mozilla.org/zh-CN/docs/Web/API/AudioContext
audioContext支持设置采样率，这部分代码是否可以修改成可动态配置的呢
`
Recorder.Support=function(set){
  //....
  //不能反复构造，低版本number of hardware contexts reached maximum (6)
  Recorder.Ctx = new AC({
    sampleRate:set.sampleRate
  });
  //....
}
`

**Comment by xiangyuecn** [comment]
需要进行配置就直接改这个源码就行了，这个配置值对最终的结果并没有起到什么作用
