### ISSUE TITLE
一个实时监听发送pcm的问题

### ISSUE THREAD

**Issue by VictoTing** [xiangyuecn/Recorder#151]
代码参考了《【教程】【音频流】实时转码并上传-通用版》Demo,地址：https://xiangyuecn.gitee.io/recorder/assets/%E5%B7%A5%E5%85%B7-%E4%BB%A3%E7%A0%81%E8%BF%90%E8%A1%8C%E5%92%8C%E9%9D%99%E6%80%81%E5%88%86%E5%8F%91Runtime.html?jsname=teach.realtime.encode_transfer。
这是我打印的realTimeSendTryChunk.index和chunk.data
![image](https://user-images.githubusercontent.com/22724533/147633885-01e50194-5e6f-4c5c-90c7-4e0b77d9785c.png)

**Comment by xiangyuecn** [comment]
将ws.send发送出去的内容，本地另外存一份，拼接起来用URL.createObjectURL下载下来，这个文件和服务器端接收到的数据对比一下是否一致。首先确保服务器接收到的和发送的是一致的在来做后续工作
