### ISSUE TITLE
效果很赞!请问能否录扬声器播放输出的声音?,不只是麦克风输入的!

### ISSUE THREAD

**Issue by mdys** [xiangyuecn/Recorder#16]
大师你好,感谢您做的这个组件! 我想请问下能否录扬声器播放输出的声音呢?,不只是麦克风输入的!
我这边主要是做PC端浏览器应用,想实现录取电脑扬声器输出的声音,不知可否实现! 请给下指点,不胜感激!

**Comment by xiangyuecn** [comment]
没试过，应该是可以的，参考人家的文章：
https://blog.csdn.net/a250758092/article/details/84676803
