### ISSUE TITLE
咨询：对讲延迟

### ISSUE THREAD

**Issue by SuperChrisliu** [xiangyuecn/Recorder#162]
老哥，请教一下，我想实现web端和小程序1对1对讲的功能，你有测过，web端录制实时音频，通过websocket传输到另一端（小程序/web/移动端）播放，延迟能控制到多少？小程序提供的rtmp推流延迟1-2s有点大

**Comment by xiangyuecn** [comment]
延迟估计可以做到150-300ms左右，默认的 BufferSize=4096 回调一次录音数据就要4096/48000*1000=85ms，网络传输一次数据50ms起步
