### ISSUE TITLE
请问能换成es6的写法，支持导出成一个模块。

### ISSUE THREAD

**Issue by pengqiangsheng** [xiangyuecn/Recorder#17]
请问能换成es6的写法，支持导出成一个模块。
这样用vue环境就可以调用了

**Comment by xiangyuecn** [comment]
#9

**Comment by xiangyuecn** [comment]
可以尝试着导出一下Recorder这个函数试试看，我对vue不熟悉

**Comment by pengqiangsheng** [comment]
已经可以了，导出成一个模块名就行。谢啦。

**Comment by idreamin** [comment]
可以发给我看下吗

**Comment by xiangyuecn** [comment]
已提供import支持，vue里面现在可以直接 `import Recorder from ./src/recorder-core.js`这样写了。或者用`npm i recorder-core`安装后引用
