### ISSUE TITLE
苹果14 只能实现第一次录音，后面录音报错

### ISSUE THREAD

**Issue by aifusen123** [xiangyuecn/Recorder#176]
苹果14第一次获取权限可以录音，后面继续录音就会报错。

**Comment by xiangyuecn** [comment]
没办法，iOS一堆bug，哪次系统升级了可能就自己修复了，或者新版本系统带来更多bug

iOS上打开录音后，尽量不要close，就没有这么多问题，不能录音就让用户刷新一下页面

**Comment by xiangyuecn** [comment]
没办法，iOS一堆bug，哪次系统升级了可能就自己修复了，或者新版本系统带来更多bug

iOS上打开录音后，尽量不要close，就没有这么多问题，不能录音就让用户刷新一下页面

**Comment by xiangyuecn** [comment]
https://github.com/xiangyuecn/Recorder/commit/f682e7a67e8219b8e8a6355b149bd0f282b85d2f 新版本已解决了iOS16上第二次open无法录音的问题
