### ISSUE TITLE
set.Type is not a function

### ISSUE THREAD

**Issue by Andre-Wang** [xiangyuecn/Recorder#18]
setTimeout(function(){
			var t1=Date.now();
			This[set.type](res,function(blob){
				console.log("["+Date.now()+"]End",blob,duration,"编码耗时:"+(Date.now()-t1));
				True(blob,duration);
			},function(msg){
				False(msg);
			});
		});

当尝试写死type的时候，就会报错。

**Comment by xiangyuecn** [comment]
使用一个type前，需要先把相应的编码引擎也加载进来。比如mp3，需要把mp3.js和mp3-engine.js加载进来。
