### ISSUE TITLE
请问现在支持没有声音录入时音频可视化波纹也有波动效果吗

### ISSUE THREAD

**Issue by guojiongwei** [xiangyuecn/Recorder#182]
作者您好，很感谢你的封装的录音插件，现在没有声音录入时，音频可视化波纹趋近于一条线，请问现在有方式可以让没有声音录入时音频可视化波纹也有波动效果吗？

**Comment by xiangyuecn** [comment]
定时调用input方法，输入点随机的数据就有波形了，可以用正弦函数生成点比较好看的数据

**Comment by guojiongwei** [comment]
明白，多谢啦。
