### ISSUE TITLE
部分苹果手机上面录制的音频音量很低。iPhone 11--16.5。iPhone 14 Pro max--16.3。

### ISSUE THREAD

**Issue by getChange** [xiangyuecn/Recorder#185]
如题。录制完的音频下载或者audio标签本地播放音频音量很小。无法听清声音。

**Comment by getChange** [comment]
> 创建Recorder的时候在audioTrackSet参数里面把 降噪和回声消除 打开一下试试，有人反馈说有效 又有人无效
> 
> 另外可以试试把这行代码删掉，测试看看：
> 
> https://github.com/xiangyuecn/Recorder/blob/c6f9533568b06e3bc2973cf64e1714573687696f/src/recorder-core.js#L125

刚才把audioTrackSet的降噪和回声消除打开了，确实可以录了。顺道把那行代码删除了。目前来说录出来的音频在上述设备上面是没有问题的了。感谢@xiangyuecn

**Comment by xiangyuecn** [comment]
现在已经默认不关闭回声消除、降噪了，使用1.2.23061000或更新的版本无需在audioTrackSet里面打开回声消除和降噪
