### ISSUE TITLE
在vue中进行调用，第一次录音之后停止之后，再点击录音控制台会报[54:54.064 Recorder]SampleData似乎传入了未重置chunk 12>4

### ISSUE THREAD

**Issue by zhenzhenhan** [xiangyuecn/Recorder#198]
<img width="498" alt="Snipaste_2023-09-27_17-01-29" src="https://github.com/xiangyuecn/Recorder/assets/106244982/6fe8cdc5-e962-4995-9ca3-1c98208fd6fc">
<img width="674" alt="Snipaste_2023-09-27_17-03-16" src="https://github.com/xiangyuecn/Recorder/assets/106244982/f12eb0c4-0a8c-4da7-9f25-1ee5caed7f00">
请问如何解决第二次录音出现这个警告的问题。

**Comment by xiangyuecn** [comment]
开始录音的时候重置一下xxxChunk变量，设为null就行了

**Comment by zhenzhenhan** [comment]
> 开始录音的时候重置一下xxxChunk变量，设为null就行了

感谢，解决了
