### ISSUE TITLE
在chrome extension的content js环境中引入1.3.23120800版本的recorder-core不能正常工作，1.2.23070100可以正常工作。

### ISSUE THREAD

**Issue by xiaoxin123222** [xiangyuecn/Recorder#203]
![vN4QeMOpxg](https://github.com/xiangyuecn/Recorder/assets/52811332/b32b09ae-3a8a-4e18-a224-ba015398a05a)
![zhe3n75HGV](https://github.com/xiangyuecn/Recorder/assets/52811332/5ebb1610-952a-4bf3-b0b8-0bc20538de5e)

**Comment by xiangyuecn** [comment]
收到，是下面2个replace没有正常替换掉代码，没考虑到js压缩混淆工具会生成带$的变量名，下一个版本修复

https://github.com/xiangyuecn/Recorder/blob/e2702d4032b08ff9fe670b35edd04163c5d7a235/src/engine/mp3.js#L289-L301

**Comment by xiangyuecn** [comment]
新版本 1.3.23121700 已修复这个问题 https://github.com/xiangyuecn/Recorder/commit/09e5fb6bfe21c1eaa331720a8dc78531030b216a
