### ISSUE TITLE
感谢博主的无私分享，IOS不支持能否有办法解决

### ISSUE THREAD

**Issue by yuhao111** [xiangyuecn/Recorder#21]
再次感谢博主的无私分享！ 目前遇见的问题是： IOS自带的浏览器可以录音播放。但开发的APP里面集成浏览器就弹出 不支持当前浏览器！  请问有什么办法解决吗？ 麻烦给一个思路
谢谢！

**Comment by yuhao111** [comment]
补充下，APP开发的时候使用IOS自带浏览器safari 还是弹出不支持？ IOS版本是12

**Comment by xiangyuecn** [comment]
ios上除了safari能录音其他地方纯粹网页估计无解。

safari和app里面用到的WKWebView不是同一个东西，苹果没有在WKWebView开放getUserMedia能力，参考 https://forums.developer.apple.com/thread/88052

既然是自己开发的app，什么都掌握在自己手里好办很多，可以让ios开发人员实现一个原生的录音接口给网页里面调用。微信上勉强可以用公众号的录音接口。

**Comment by yuhao111** [comment]
谢谢！ 难怪我今天调试一天都没有解决！   IOS的具体方案有没有DEMO可以参照？

**Comment by yuhao111** [comment]
UIWebView 是用这个进行调用吗？

**Comment by xiangyuecn** [comment]
😅ios上的问题，我在已知问题里面还有开头 着重注明了呀。

ios app上的方案暂时没有，只有我上面的那个思路。

综合来看，app里面就不应该用我这个库，应该由app原生提供接口，供网页来调用，这样Android和ios上都是一致的，会简单和统一很多。 

网页版里面才用getUserMedia去录音，双管齐下基本就完美了。

**Comment by yuhao111** [comment]
我看到了！ APP提供原生接口来调！ 这个有没有DEMO可以参考呢！

**Comment by yuhao111** [comment]
WebViewJavascriptBridge  这个可以吗

**Comment by xiangyuecn** [comment]
没有具体的demo 😶，我不是搞ios的，不过可以搜索：`ios hybrid app 交互` 实现起来应该也蛮简单

**Comment by xiangyuecn** [comment]
就是 WebViewJavascriptBridge 这种类似的 交互手段

**Comment by yuhao111** [comment]
感谢博主！
