### ISSUE TITLE
Cannot read properties of undefined (reading 'i18n')

### ISSUE THREAD

**Issue by SHSSNN** [xiangyuecn/Recorder#211]
页面引入任何一个插件或者格式文件都报这个错误,
<img width="339" alt="微信图片_20240229160626" src="https://github.com/xiangyuecn/Recorder/assets/155428274/f673c7bf-fc35-4c77-a06d-b7f2622a2fa8">
<img width="383" alt="微信图片_20240229155836" src="https://github.com/xiangyuecn/Recorder/assets/155428274/b74cd73b-5bf6-4447-8e39-6a07c8c05b58">
我使用的框架是vite+vue3+ts

**Comment by xiangyuecn** [comment]
已收到群里反馈，是因为类似 `import Recorder from 'recorder-core'` 但未引用Recorder导致的此import被优化干掉了，只需随便调用一下Recorder变量保证强引用即可

**Comment by SHSSNN** [comment]
多谢指导

**Comment by krmao** [comment]
recoder import must be first and then import wav and waview

```
import Recorder from 'recorder-core';
import 'recorder-core/src/engine/wav';
import 'recorder-core/src/extensions/waveview';
// https://github.com/xiangyuecn/Recorder/issues/211
Recorder.ConnectEnableWorklet = false;
```
