### ISSUE TITLE
关于样式

### ISSUE THREAD

**Issue by maintheme-mili** [xiangyuecn/Recorder#22]
作为一名前端爱好者 功能确实吊 页面看着是真的难受

**Comment by xiangyuecn** [comment]
手机上看稍微好点。电脑上没限制宽度，看起来左边一坨坨，右边太稀疏，所以难受🙈，这个测试界面是我没开源时自己测试用的，后面拿过来就没有美化，反而不停的在上面加东西，就变成了现在这个模样。最原始的粗犷。

有时间我看看怎么搞漂亮点😊

**Comment by xiangyuecn** [comment]
已经稍微美化了一点，整个测试页面按功能上分成不同的块，居中显示了一下比以前一大坨好很多了😁
