### ISSUE TITLE
结束录音失败：未加载unknown编码器

### ISSUE THREAD

**Issue by Oorpow** [xiangyuecn/Recorder#229]
我参考了demo中 [【教程】实时转码并上传]，由于我要获取最终的音频文件，所以我将`rec.close()`，替换成了`rec.stop()`用来取blob然后我的页面出现了下面的错误：
> 结束录音失败：未加载unknown编码器，请尝试到Recorder的src/engine内找到unknown的编码器并加载

我在对应的engine目录下也没看到有这个unknown编码器，请问怎么解决？

**Comment by xiangyuecn** [comment]
把type:"unknown"改成 type:"mp3"之类的你需要的格式，删掉类似 buffers[i]=null 的释放代码

**Comment by Oorpow** [comment]
好的，感谢回答
