### ISSUE TITLE
mp3等录制结果获取问题

### ISSUE THREAD

**Issue by Titans1001** [xiangyuecn/Recorder#236]
怎么能不通过stop 回调来获取mp3 blob ,而是在录制过程或者 录制暂停而非录制 stop 获取 mp3 blob

**Comment by xiangyuecn** [comment]
录音配置里面提供 takeoffEncodeChunk 回调，可以实时获取到mp3二进制数据

**Comment by Titans1001** [comment]
ok了，3Q大佬

**Comment by Titans1001** [comment]
a
