### ISSUE TITLE
IOS打包app 能进行录音以及播放吗？ 还需上传到服务器的

### ISSUE THREAD

**Issue by NetZAL** [xiangyuecn/Recorder#24]
现在 我有一个开发是这样的， 使用ionic1 进行打包， 在真机上调试， 能进行录音， 以及获取录音的所在路径吗？ 或者说不需要路径， 可以将获取的录音变为base64文件吗

**Comment by xiangyuecn** [comment]
ios 里面的webview不支持h5录音。需要app原生代码（oc、swi???）提供支持。

比如你可以用WebViewJavascriptBridge 来实现 RecordApp  Native里面用到的3个接口，然后直接RecordApp 就能完成录音，就算脱离IOS环境，RecordApp会自动处理。

https://github.com/xiangyuecn/Recorder/blob/0af9242029c025f1cef94bef7908cd8a608e6205/src/app-support/app-native-support.js#L52-L63

最后获得录音文件的问题，不管在哪用这个，获取录音文件的方式都是统一的，结束录音时会得到blob二进制文件对象，blob：可读取、可播放、可上传，具体参考首页文档里的例子。

**Comment by xiangyuecn** [comment]
复杂的一逼，估计实现起来要花点功夫。就算我自己去实现app h5里面去录音，这个思路是不会变的（就像支付）。ios就是一个累赘，看着搞吧，实在不行提前放弃支持说不定是个更好的选择😂

**Comment by NetZAL** [comment]
哈哈， 是啊， 为什么 IOS 跟 Android 会有那么大区别， 同一个插件， Android 完美运行， 在IOS下没作用。
对了， 我还有一个问题， 想着提问了我就顺便想问问， 为什么我的 cordova.file.* 后面所有的路径， 在我的苹果手机真机上都是 null ， 可是网上说有些路径是可用的啊， 为什么我的都是null？ 你是否有这方面经验呢？




------------------ 原始邮件 ------------------
发件人: "高坚果"<notifications@github.com>; 
发送时间: 2019年4月29日(星期一) 中午11:59
收件人: "xiangyuecn/Recorder"<Recorder@noreply.github.com>; 
抄送: "透析童年丶"<969807344@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xiangyuecn/Recorder] IOS打包app 能进行录音以及播放吗？ 还需上传到服务器的 (#24)




复杂的一逼，估计实现起来要花点功夫。就算我自己去实现app h5里面去录音，这个思路是不会变的（就像支付）。ios就是一个累赘，看着搞吧，实在不行提前放弃支持说不定是个更好的选择😂

**Comment by xiangyuecn** [comment]
对ios不熟， cordova.file.* 这个问题回答不了，去他们论坛溜达溜达说不定会有收获😁
