### ISSUE TITLE
IOS播放PCM音频流数据没有声音怎么解决？

### ISSUE THREAD

**Issue by monttailee** [xiangyuecn/Recorder#240]
IOS播放PCM音频流数据没有声音怎么解决？

**Comment by xiangyuecn** [comment]
iOS版本多少，日志里面有没有什么错误信息

**Comment by monttailee** [comment]
ios17.5.1

**Comment by monttailee** [comment]
> iOS版本多少，日志里面有没有什么错误信息
ios17.5.1，有个报错：arraybuffer length minus the byteoffset is not a multiple of the element size

**Comment by xiangyuecn** [comment]
16位的pcm数据是双字节，长度必须是2的倍数，最好让服务器那边去做正确处理，不然就前端把结尾的多的一个字节存起来，下次收到数据时拼接到数据开头

**Comment by monttailee** [comment]
> 16位的pcm数据是双字节，长度必须是2的倍数，最好让服务器那边去做正确处理，不然就前端把结尾的多的一个字节存起来，下次收到数据时拼接到数据开头

后端数据应该没问题吧，安卓跟ios15以下的手机能正常播放声音，ios高版本的就不可以?

**Comment by monttailee** [comment]
> > 16位的pcm数据是双字节，长度必须是2的倍数，最好让服务器那边去做正确处理，不然就前端把结尾的多的一个字节存起来，下次收到数据时拼接到数据开头
> 
> 后端数据应该没问题吧，安卓跟ios15以下的手机能正常播放声音，ios高版本的就不可以?
