### ISSUE TITLE
用最近这版做了测试程序，录自己的声音还挺好，但是录一首歌的话，效果就比较差，怎么解决？

### ISSUE THREAD

**Issue by xiyudaxia** [xiangyuecn/Recorder#25]
用最近这版做了测试程序，采样率设置到了48000，比特率到了320，录自己的声音还挺好，但是录一首歌的话（自己手机播放自己录），效果比较差，请问有什么办法解决？

**Comment by xiyudaxia** [comment]
补充一下，是一首曲子，本来想用这种办法，适应朗读这种场景（用户对着手机朗读+播放背景音乐），不理想，后来直接只放音乐，效果还是没有改观，请指教

**Comment by xiangyuecn** [comment]
你可以试一下wav格式，48000hz，16位编码录音的音质，这个编码的音频数据是浏览器接收到麦克风原始数据流，并且没有转码。应该算是最接近手机接收到的声音了。其他编码格式是有损的。

音质问题和麦克风有很大关系，也许耳麦会更好些，或者话筒。猜的没试过。

另外手机麦克风凑近播放音乐的喇叭录音音质会好很多，跟录音距离也有很大关系。

### 另外核心在于：
> 本库期待的使用场景是简短的语音录制，因此音质只要不比高品质的感觉差太多就行
