### ISSUE TITLE
实时往后台传

### ISSUE THREAD

**Issue by shanliangmaoxian** [xiangyuecn/Recorder#26]
请问 我在h5录制的时候 需要实时往后台传递音频流  是不是只需要传递 onProcess 中的 buffers 就可以

**Comment by xiangyuecn** [comment]
可以，buffers[buffers.length-1]就是当前从浏览器接收到的pcm原始数据。

这个音频的采样率一般是48000，单声道，1秒接近48k数据，目测要压缩一下😂

**Comment by shanliangmaoxian** [comment]
我后台接收 buffer 通过io 生成 wav文件  生成后的文件 不能打开 是为什么呢

**Comment by xiangyuecn** [comment]
参考wav文件生成代码，自己研究一下：
https://github.com/xiangyuecn/Recorder/blob/0af9242029c025f1cef94bef7908cd8a608e6205/src/engine/wav.js#L76-L78

1. 确保浏览器端发送出来的数据 和 后端接收到的数据 的一致性
2. 验证浏览器端的数据能够生成有效的wav文件
3. 验证后端能把数据封装成有效的wav文件

**Comment by shanliangmaoxian** [comment]
前端生成wav有效, buffer数据也是一直的  难道要 把pcm转为 wav格式的 给后台

**Comment by xiangyuecn** [comment]
可以尝试一下，不过目测作用不大

**Comment by shanliangmaoxian** [comment]
试过了 没有用  为什么 前台 ok  后台 实时接收buffer 生成 wav就不行  尴尬～

**Comment by shanliangmaoxian** [comment]
还是 搞不定 可以加一下 qq嘛  872385796

**Comment by xiangyuecn** [comment]
😢😢😂
