### ISSUE TITLE
是否支持实时拍照？

### ISSUE THREAD

**Issue by chen-yt** [xiangyuecn/Recorder#27]
看了你的原理好像是通过navigation.getUserMedia实现的，但我调试的时候，iOS的微信好像不支持这个接口？想问下您是怎么实现的

**Comment by xiangyuecn** [comment]
嗯，ios 目前除了Safari支持getUserMedia，其他浏览器一律都没有开放支持，相应的功能都不能使用。

ios微信里面我提供的解决办法是使用微信自家的jssdk来录音，并没有走getUserMedia。

拍照？😂  你那边试的我的两个测试页面是不是有一个页面在ios微信里面能够录音呀？

**Comment by SAMZONG** [comment]
插一句，ios是通过Safari的getUserMedia解决，微信是使用微信自身的jssdk绑定，Android这块怎么实现的方式比较好呢，另外一点，从点开页面到最终弹出获取权限申请，页面还是比较慢的

**Comment by xiangyuecn** [comment]
@SAMZONG 哈哈，Android就没什么要考虑的，直接h5录音一把梭，几乎不用考虑兼容性。

要不是苹果市场份额大了点，鬼才去兼容ios 😂，另外目测是苹果故意在UI? WK? WebView里面做的限制。

至于权限，瑟瑟发抖 不敢去研究😊

**Comment by SAMZONG** [comment]
@xiangyuecn 所以说在android 应该不会存在兼容性问题是吧？

**Comment by xiangyuecn** [comment]
@SAMZONG 几乎不用考虑，Android5.0 以上不管是自带浏览器还是微信、chrome都支持的不错。但有些rom国产浏览器表现过于奇特，没法管也管不了，不管也罢😂 #29
