### ISSUE TITLE
bug一大推

### ISSUE THREAD

**Issue by jiangwuzhang** [xiangyuecn/Recorder#28]
就这种代码还好意思往上提，bug一大堆，微信，hy app都用不了

**Comment by xiangyuecn** [comment]
😂这玩意就像兼容ie6一样，多多少是会有毛病的。

另外能把 你发现用不了的浏览器的UserAgent发来研究一下 就最好了（非IOS，IOS的发了目前也解决不了）

**Comment by jiangwuzhang** [comment]
可能是我学艺不精吧。。我用cordova内嵌这个网页，发现不能用。。
只是觉得h5现在拿来录音，是否还不成熟。

**Comment by xiangyuecn** [comment]
Android上问题可能会简单些。Android 5.0以上webview基本上都能完整的支持录音功能，就是权限问题如果没处理好就容易出问题。

不像手机里面安装的浏览器录音时会弹提示框询问用户。自己直接或间接套webview需要自行处理权限：一个是webview的权限，另一个是app的权限。

**Comment by jiangwuzhang** [comment]
> Android上问题可能会简单些。Android 5.0以上webview基本上都能完整的支持录音功能，就是权限问题如果没处理好就容易出问题。
> 
> 不像手机里面安装的浏览器录音时会弹提示框询问用户。自己直接或间接套webview需要自行处理权限：一个是webview的权限，另一个是app的权限。

就是权限提示框询问用户的问题。如果我用安卓的cordova内嵌。点申请录音权限不会提示用户是否赋权，而是直接失败。如果去应用中心给这个app赋予可录音的权限，那就可以录音了。（其实没有改之前，录音权限是询问，压根就没询问）。
