### ISSUE TITLE
设备固定的情况下，录音文件的生成速度可以通过做什么进行提升呢？

### ISSUE THREAD

**Issue by Perjak** [xiangyuecn/Recorder#30]
最近做一个问卷录音的项目，十分钟的录音生成文件大概需要一分多钟，请问生成速度还有可优化的空间吗

**Comment by Perjak** [comment]
补充一下，用的是mp3格式的。

**Comment by xiangyuecn** [comment]
用worker，边录边转码，最后生成录音文件非常快。需要自己在onaudioprocess重写代码，就能边录音后台边转码

**Comment by Perjak** [comment]
好的，多谢你提供思路，我试试 @xiangyuecn
