### ISSUE TITLE
stop failed

### ISSUE THREAD

**Issue by myCharacter** [xiangyuecn/Recorder#31]
我们实现类似微信的发送语音功能但是 我按下录音 松开的时候 提示我 stop 失败

**Comment by SAMZONG** [comment]
Hi 请问，你们在app里面是如何实现的呢？对应解决方案可以分享下吗？

**Comment by xiangyuecn** [comment]
@myCharacter 有没有更多的细节，比如UserAgent。在松开结束录音前是否已明确正常的开始了录音。

如果检查都没有问题，仍然stop失败，可以试试打开测试页面，在相同的环境下是否也会有问题。

**Comment by xiangyuecn** [comment]
@SAMZONG 我前段时间在Android里面调用原生接口实现了一套，发现最终用原生功能来进行编码mp3等格式很是复杂，需要引入so，包括ios也是一样，最后放弃了用原生代码来进行编码。采用将app采集到的pcm实时传回网页，让Recorder去编码，Android代码量减少不少

**Comment by SAMZONG** [comment]
能用wav格式，进行base64编码后的数据，Recorder这边能解析吗？ 另外实时传回是怎么理解？ 

有对应的API么介绍嘛

**Comment by xiangyuecn** [comment]
@SAMZONG Recorder.wav没有提供解码函数（amr提供了amr解码），你可以自己参照wav里面的编码函数自行写一个解码成pcm的函数，预计代码量也不会超过100行。解码后扔给Recorder.mock就能进行转码之类的操作了。

上面提到的app原生收到录音数据后实时回传给js的原理和`Recorder.prototype._start`中`process.onaudioprocess`回调差不多，涉及到网页和app原生数据交互，并没有什么高大上的原理。
