### ISSUE TITLE
过滤杂音应该怎么做，就是音量小的忽略掉

### ISSUE THREAD

**Issue by Daisny** [xiangyuecn/Recorder#32]
如题，大佬有招吗

**Comment by xiangyuecn** [comment]
不是这方面的专业，也不敢说话，因为确实不懂，以外行的眼光来看那是相当复杂的实现。坐等相关方面的大佬出现😊

不过还是可以提供部分线索：`PCM降噪` `WAVE降噪` 搜索研究研究

**Comment by xiangyuecn** [comment]
新版本set里面支持传递getUserMedia的audio参数set.audioTrackSet，回声可以尝试调节echoCancellation，降噪可调节noiseSuppression，但这些参数不一定会生效

https://github.com/xiangyuecn/Recorder/blob/ddd980e8e70715658519eee8d2fc8417b6fbca0c/README.md#L439-L442

#109
