### ISSUE TITLE
获取的blob对象如何调用百度语音识别接口呢？

### ISSUE THREAD

**Issue by leiky** [xiangyuecn/Recorder#35]
如题，

**Comment by xiangyuecn** [comment]
😢

把blob当文件来看就ok了，可以用multipart/form-data上传二进制文件，也可以把内容读取成base64纯文本，这两种简单些。

如果用百度的语音rest接口，也许需要自己的服务器做跳板，那么就只涉及到把blob内容传给自己的服务器，自由的很，想怎么传就怎么传。至于后端用raw还是json调用百度接口，那就让后端去折腾。

参考readme里面的上传示例。

**Comment by leiky** [comment]
请问前端无法实现吗？如果想要纯前端录音，然后获取base64转码的二进制音频文件 ，之后调用百度接口可行吗？另外还想请教下这个项目是单声道，采样率16000的吗。

**Comment by xiangyuecn** [comment]
如果百度提供了前端可以调用的接口，那就可以直接用。

不过百度似乎并没有开放前端直接调的这种接口，rest的都是针对后端用的。

这个库只支持单声道；采样率随便，默认16000

**Comment by Lagomoro** [comment]
blobdata:    return new Blob([data], {type: 'audio/pcm'});

key code:
Baidu_AipSpeech_SDK.prototype.recognize = function(blobdata, callback){
    callback = this.getCallback(callback);
    this.recognizing = true;

    var that = this;
    var fileReader = new FileReader();
    fileReader.onload = function() {
        var voiceBase64 = new Buffer(this.result);
        that.client.recognize(voiceBase64, 'pcm', 16000).then(function(result) {
            that.recognizing = false;
            $gameTemp.status("待机中");
            console.log(JSON.stringify(result));
            var text = result.result ? result.result[0] : result.err_msg;
            text = text.substring(0, text.length -1);
            if(text === "speech quality error" ||text === "recognition error"){
                callback.fail.call(callback.owner);
            } else {
                callback.success.call(callback.owner, text);
            }
        }, function(err) {
            that.recognizing = false;
            callerr.error.call(callback.owner, err);
        });
    };
    fileReader.readAsArrayBuffer(blobdata);
};

**Comment by Lagomoro** [comment]
blobdata: return new Blob([data], {type: 'audio/pcm'});

key code:
`
Baidu_AipSpeech_SDK.prototype.recognize = function(blobdata, callback){
callback = this.getCallback(callback);
this.recognizing = true;
var that = this;
var fileReader = new FileReader();
fileReader.onload = function() {
    var voiceBase64 = new Buffer(this.result);
    that.client.recognize(voiceBase64, 'pcm', 16000).then(function(result) {
        that.recognizing = false;
        $gameTemp.status("待机中");
        console.log(JSON.stringify(result));
        var text = result.result ? result.result[0] : result.err_msg;
        text = text.substring(0, text.length -1);
        if(text === "speech quality error" ||text === "recognition error"){
            callback.fail.call(callback.owner);
        } else {
            callback.success.call(callback.owner, text);
        }
    }, function(err) {
        that.recognizing = false;
        callerr.error.call(callback.owner, err);
    });
};
fileReader.readAsArrayBuffer(blobdata);
};`

**Comment by Lagomoro** [comment]
blobdata: return new Blob([data], {type: 'audio/pcm'});
key code:
`Baidu_AipSpeech_SDK.prototype.recognize = function(blobdata, callback){
    callback = this.getCallback(callback);
    this.recognizing = true;

    var that = this;
    var fileReader = new FileReader();
    fileReader.onload = function() {
        var voiceBase64 = new Buffer(this.result);
        that.client.recognize(voiceBase64, 'pcm', 16000).then(function(result) {
            that.recognizing = false;
            $gameTemp.status("待机中");
            console.log(JSON.stringify(result));
            var text = result.result ? result.result[0] : result.err_msg;
            text = text.substring(0, text.length -1);
            if(text === "speech quality error" ||text === "recognition error"){
                callback.fail.call(callback.owner);
            } else {
                callback.success.call(callback.owner, text);
            }
        }, function(err) {
            that.recognizing = false;
            callerr.error.call(callback.owner, err);
        });
    };
    fileReader.readAsArrayBuffer(blobdata);
};`

**Comment by mebtte** [comment]
在chrome测试wav设置采样率不起作用
