### ISSUE TITLE
安卓app中webview调用录音失败

### ISSUE THREAD

**Issue by NecisDJ** [xiangyuecn/Recorder#36]
使用RecordApp，在安卓中调用录音失败，错误提示如下：
<img width="494" alt="WX20190718-162150@2x" src="https://user-images.githubusercontent.com/17264672/61441476-46c50f00-a978-11e9-9eb0-adb7af165420.png">

之前是调用Recorder的时候安卓webview测试是好的，是否和RecordApp有关呢？

**Comment by xiangyuecn** [comment]
里面用到了Default，Default的底层实现就是Recorder，请求权限的时候最终调用的还是Recorder.open。

但你提到之前是调用Recorder是好的，要不再直接用Recorder的试一下看看能不能录音。
