### ISSUE TITLE
采样率不起作用？

### ISSUE THREAD

**Issue by mebtte** [xiangyuecn/Recorder#37]
```js
const recorder = new Recorder({ type: 'wav', sampleRate: 16000 });
```
设置采样率无效
![image](https://user-images.githubusercontent.com/8120967/61579740-b0d9e180-ab3b-11e9-83f1-865ff76ce80b.png)
依旧是浏览器默认的`44100`

**Comment by xiangyuecn** [comment]
图片中拿到的AudioBuffer是音频源的原始数据，是浏览器的采样率是多少，它的采样率就是多少。

配置的采样率会在最终编码时生效，最终结果wav格式的采样率其实是可以通过文件大小计算出来的：65430/2/2.043=16013≈16000
