### ISSUE TITLE
能否支持 webpack import

### ISSUE THREAD

**Issue by falseLuffy** [xiangyuecn/Recorder#38]

**Comment by xiangyuecn** [comment]
试试：直接import，通过window.Recorder调用。没有试过😂，如果可用麻烦反馈一下哈

**Comment by falseLuffy** [comment]
自问自答
使用webpack开发又不想全局引用的话， 可以使用exports-loader
具体使用如下
`
import Recorder from 'exports-loader?window.Recorder!../../js/recorder.wav.min.js'
`

**Comment by xiangyuecn** [comment]
没试过webpack，但还是觉得蛮实用，我把这个issue加到readme里面

**Comment by xiangyuecn** [comment]
已提供import支持，现在可以直接 `import Recorder from recorder.wav.min.js`这样写了
