### ISSUE TITLE
open的异步特别慢,可能被优化吗

### ISSUE THREAD

**Issue by xiaohailiang** [xiangyuecn/Recorder#39]
模拟微信发送语音消息, 点击语音键, 调用open 在open的回调里面 调用start, 此时
基本上4-5秒之后才能start, 这个体验很不好阿

**Comment by xiangyuecn** [comment]
原因在于open的时候会调用getUserMedia方法，在用户已授权的情况下，此方法不同浏览器回调速度不一样，有的特别慢。

解决方法：整个页面加载完成后先调用一次open（如果成功的话），不要调用close（页面被关闭时浏览器会自动清理，或自行在页面被卸载时清理一下）。这样每次start可以不用等getUserMedia龟速回调了。

注：不调用close在Safari上第二次录音是会有问题的（苹果家的问题），Android上不受影响。

**Comment by xiaohailiang** [comment]
对你说的问题我都经历过了.现在只能加一些交互来改善体验了.

**Comment by xiangyuecn** [comment]
可以的，加油😎
