### ISSUE TITLE
ios授权麦克风刷新后重复提示

### ISSUE THREAD

**Issue by xiayu1017** [xiangyuecn/Recorder#40]
ios Safari，12系统，第一次提示授权麦克风，刷新完网页，再次还是询问授权麦克风

**Comment by xiangyuecn** [comment]
Safari上是这样的，每次打开页面都会弹权限对话框。

Android上就更加五花八门了，不过大部分只要没有退出app就不会再弹。微信上虽然更加五花八门，不过目前来看只要授权一次好几天也不会再弹。firefox智障只要调用了close，再次open一定会弹
