### ISSUE TITLE
iPhone通过.mobileconfig安装的不能录音有人遇到过么

### ISSUE THREAD

**Issue by saurybin** [xiangyuecn/Recorder#41]
如题，通过这种模式安装，打开后不能询问用户是否打开录音。
这种模式跟添加到主屏幕的效果差不多，如果去掉全屏的代码就可以，如下。
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
Orz找不到解决方案了。

**Comment by xiangyuecn** [comment]
看来WebClip调起的全屏Safari也被限制😁 苹果真恶心😒

![搜狗截图20190815172030](https://user-images.githubusercontent.com/13175029/63086103-b59a8580-bf81-11e9-9ea1-7e9338c3d0d2.png)
