### ISSUE TITLE
recorder.mp3.min.js?f1e7:38 mp3 worker剩1个未释放,出现这种情况要怎么办

### ISSUE THREAD

**Issue by zhengyn0001** [xiangyuecn/Recorder#43]
![image](https://user-images.githubusercontent.com/51322469/63841266-13cd5c80-c9b5-11e9-8ab7-520493e6539f.png)

**Comment by xiangyuecn** [comment]
是哪里调用了start后没有调用stop吧，自己检查一下看看。

是允许同时进行多个有效的start调用，最后一个stop前的所有stop调用都会有警告，只要最后一个stop没有警告，就是正常的。

**Comment by zhengyn0001** [comment]
那我怎么知道是是不是最后一个stop弹出的警告发自我的华为手机-------- 原始邮件 --------发件人： 高坚果 <notifications@github.com>日期： 2019年8月28日周三 17:50收件人： xiangyuecn/Recorder <Recorder@noreply.github.com>抄送： zhengyn0001 <1046611633@qq.com>, Author <author@noreply.github.com>主    题： Re: [xiangyuecn/Recorder] recorder.mp3.min.js?f1e7:38 mp3 worker剩1个未释放,出现这种情况要怎么办 (#43)是哪里调用了start后没有调用stop吧，自己检查一下看看。

是允许同时进行多个有效的start调用，最后一个stop前的所有stop调用都会有警告，只要最后一个stop没有警告，就是正常的。

**Comment by xiangyuecn** [comment]
笨办法：数一下代码里面有几个start，然后数一下stop是不是比start更少
