### ISSUE TITLE
ios11.3无法使用formData上传blob文件？

### ISSUE THREAD

**Issue by cherish1260** [xiangyuecn/Recorder#44]
设备：ios11.3微信h5
使用formData上传，发现上传到后台的数据file不为空，但是内容没有了，想问一下有没有遇到这个问题的，只有ios几台设备存在这个问题

**Comment by xiangyuecn** [comment]
是已经解决了吗，刚测试完就发现这个issue已经close了😂

特意在RecordApp Demo页面IOS微信里面测试发现，formdata上传blob正常。（微信没有小号，还从未在ios里面测试过，以前都是Android里面测试，刚才全部测试了一遍，和Android没区别😁）

测试代码：
``` javascript
var arr=Object.keys(recblob).sort()
var blob=recblob[arr[arr.length-1]].blob

var form=new FormData();
form.append("upfile",blob,"recorder.mp3"); //和普通form表单并无二致，后端接收到upfile参数的文件，文件名为recorder.mp3
//...其他表单参数
$.ajax({
    url:"/ssss" //上传接口地址
    ,type:"POST"
    ,contentType:false //让xhr自动处理Content-Type header，multipart/form-data需要生成随机的boundary
    ,processData:false //不要处理data，让xhr自动处理
    ,data:form
    ,success:function(v){
        console.log("上传成功",v);
    }
    ,error:function(s){
        console.error("上传失败",s);
    }
});
```

请求抓包：

![](https://user-images.githubusercontent.com/13175029/63991093-fa452580-cb18-11e9-9a74-77d431a2bdb1.png)

**Comment by cherish1260** [comment]
你好，感谢回复，我之前转成了File去上传的，在ios11.3是不成功的，其他高版本手机可以，后来使用原来的blob，两端都可以了

**Comment by cherish1260** [comment]
> 是已经解决了吗，刚测试完就发现这个issue已经close了😂
> 
> 特意在RecordApp Demo页面IOS微信里面测试发现，formdata上传blob正常。（微信没有小号，还从未在ios里面测试过，以前都是Android里面测试，刚才全部测试了一遍，和Android没区别😁）
> 
> 测试代码：
> 
> ```js
> var arr=Object.keys(recblob).sort()
> var blob=recblob[arr[arr.length-1]].blob
> 
> var form=new FormData();
> form.append("upfile",blob,"recorder.mp3"); //和普通form表单并无二致，后端接收到upfile参数的文件，文件名为recorder.mp3
> //...其他表单参数
> $.ajax({
>     url:"/ssss" //上传接口地址
>     ,type:"POST"
>     ,contentType:false //让xhr自动处理Content-Type header，multipart/form-data需要生成随机的boundary
>     ,processData:false //不要处理data，让xhr自动处理
>     ,data:form
>     ,success:function(v){
>         console.log("上传成功",v);
>     }
>     ,error:function(s){
>         console.error("上传失败",s);
>     }
> });
> ```
> 
> 请求抓包：
> 
> ![](https://user-images.githubusercontent.com/13175029/63991093-fa452580-cb18-11e9-9a74-77d431a2bdb1.png)

你好，感谢回复，我之前转成了File去上传的，在ios11.3是不成功的，其他高版本手机可以，后来使用原来的blob，现在都可以了
