### ISSUE TITLE
iPhone 接藍芽耳機, 錄音會失敗

### ISSUE THREAD

**Issue by todomato** [xiangyuecn/Recorder#45]
目前使用者用一般操作錄音正常, 但使用者切換用藍芽耳機來錄音時, 接收的音檔都沒有聲音
或是者有錄到音,但只有第一秒有錄到,後面就完全沒聲音

請問有遇過類似狀況嗎?

**Comment by xiangyuecn** [comment]
也许并非是使用了蓝牙耳机的问题，已知Safari在录音后未调用close然后继续新的录音是会有问题的，表现为没有任何声音回调。因此需要排除一下这个问题的干扰：

1. 手机连接蓝牙耳机
2. 新打开或刷新录音页面
3. 进行首次录音，看看结果如何

这样试试看看有没有问题
