### ISSUE TITLE
开始录音之后会监听不到touchend事件

### ISSUE THREAD

**Issue by zhengyn0001** [xiangyuecn/Recorder#46]
我的代码的实现是按住开始录音，之后松开结束录音，可是在安卓的app里面的h5页面能监听到touchstart,不能监听到touchend

**Comment by xiangyuecn** [comment]
这问题就复杂了。。。

可以先把所有录音相关的代码和库全部移除试试长按后能不能收到touchend

如果能收到touchend，在加上JsBridge任意数据收发再测一遍，如果有JsBridge的话

如果能收到touchend，把录音功能一点点的加上，先加open测一遍，一直测到stop看看是哪个地方加上后有问题，然后好针对性的解决

**Comment by xiangyuecn** [comment]
如果用的JsBridge，并且是重写的prompt，可能是会有问题，有时间我测试一下prompt

**Comment by xiangyuecn** [comment]
实锤了，Android App demo里面的JsBridge会导致不会触发touchend。

纯粹的H5录音就没有这个问题，IOS App的JsBridge也没有这个问题，有时间再研究研究这个bug

**Comment by zhengyn0001** [comment]
我发现这边还是有问题啊，有时可以松开手结束，有时不行，我发现程序在不断的进行window.AppJsBridgeRequest这个方法的执行
![image](https://user-images.githubusercontent.com/51322469/68387805-28d72080-019a-11ea-8601-adeb75a6e4c3.png)
![image](https://user-images.githubusercontent.com/51322469/68387855-4310fe80-019a-11ea-9a4e-76dce771435a.png)

**Comment by xiangyuecn** [comment]
核心的action没有打印出来。应该是recordAlive调用，native-config中录音开始后会开启一个5秒的定时器，定时发送recordAlive心跳，Native层超过时间没有收到心跳就会自动关闭录音。这就导致了AppJsBridgeRequest在不停的被调用。

你试试我的那个Android demo app是不是也会有时松开手不能停止录音，我这反复测不出来这个情况现在。

注意：H5里面touch事件除了要监听touchend，还要监听touchcancel，这两个都算手松开了

**Comment by zhengyn0001** [comment]
我明天试试发自我的华为手机-------- 原始邮件 --------发件人： 高坚果 <notifications@github.com>日期： 2019年11月7日周四 23:19收件人： xiangyuecn/Recorder <Recorder@noreply.github.com>抄送： zhengyn0001 <1046611633@qq.com>, State change <state_change@noreply.github.com>主    题： Re: [xiangyuecn/Recorder] 开始录音之后会监听不到touchend事件 (#46)核心的action没有打印出来。应该是recordAlive调用，native-config中录音开始后会开启一个5秒的定时器，定时发送recordAlive心跳，Native层超过时间没有收到心跳就会自动关闭录音。这就导致了AppJsBridgeRequest在不停的被调用。
你试试我的那个Android demo app是不是也会有时松开手不能停止录音，我这反复测不出来这个情况现在。
注意：H5里面touch事件除了要监听touchend，还要监听touchcancel，这两个都算手松开了

**Comment by zhengyn0001** [comment]
我刚试了，给其中的录制按钮加上touchstart,touchend时间，按就了就会出现那个长按复制的字，然后松开手录音没有结束，以及我这边的项目的touchcancal执行的时间好像不太对，感觉是刚开始就执行了touchcancel,松开手还是没有监听到touchend的打印

![image](https://user-images.githubusercontent.com/51322469/68448249-d63f4800-021d-11ea-91b2-7c838ccd8acd.png)

**Comment by xiangyuecn** [comment]
看你截图那是一调用请求权限就立马执行了touchcancel，Android立马打个断点看看是不是走了Activity.requestPermissions方法，只要走了这个方法就会导致touchcancel。 我后面是把checkSelfPermission加了回去，只要有权限了就不走Activity.requestPermissions，就没有touchcancel了。

另外长按出现复制这个可以参考我的代码，注意首尾这两行：

https://github.com/xiangyuecn/Recorder/blob/609e72badf3a179539826c832b7cee59fb2f8ce6/assets/zdemo.index.webrtc.js#L183-L203

**Comment by zhengyn0001** [comment]
![image](https://user-images.githubusercontent.com/51322469/68540664-bdc35f00-03d0-11ea-929e-1623815ba3ee.png)
狂点录音按钮， 录音报错， 会触发destroy函数， 但是其他线程引用了main.Log 打日志， 但是main已经是 null
![image](https://user-images.githubusercontent.com/51322469/68540671-c9af2100-03d0-11ea-9e1c-85ff1bcae4f2.png)
![image](https://user-images.githubusercontent.com/51322469/68540672-cddb3e80-03d0-11ea-8cc7-00d8d2de8037.png)

**Comment by xiangyuecn** [comment]
我研究研究，估计ios也会有这个问题😂

**Comment by xiangyuecn** [comment]
Android里面 构造函数 和 destroy 加了一个synchronized就没有多大问题了，其他线程同步一下就没有这个狂点导致崩溃的了
