### ISSUE TITLE
是否可以支持采集PCM裸流

### ISSUE THREAD

**Issue by bigbeef** [xiangyuecn/Recorder#47]

**Comment by yrain** [comment]
同问一下

**Comment by xiangyuecn** [comment]
录音实时回调onProcess中的buffers就是pcm格式的（16位），简单加个wav头就变成了wav文件。

或者录制wav格式，录音结束得到的blob去掉wav头就可以了
https://github.com/xiangyuecn/Recorder/blob/646df8a8650ae3acad30ca9a9f29999ce94384c4/README.md#L364-L366

也不知道你问的是不是这个😂

**Comment by bigbeef** [comment]
我想实时获取PCM流推向服务器，实现音频实时监听

**Comment by bigbeef** [comment]
已经完美实现，特意贴上自己的代码

```vue
       let webSocket = new WebSocket(wsUrl);
        webSocket.binaryType = 'arraybuffer';

        let chunkInfo;
        let rec = Recorder({
          type: 'wav', bitRate: 16, sampleRate: 8000, bufferSize: 2048, onProcess:
              function(buffers, powerLevel, bufferDuration, bufferSampleRate) {
                chunkInfo = Recorder.SampleData(buffers, bufferSampleRate, rec.set.sampleRate, chunkInfo);
                webSocket.send(chunkInfo.data);
              },
              }
        });
        //开始录音
        rec.open(function() {
          rec.start();
         });
```

**Comment by xiaoxiaoqian1217** [comment]
> 录音实时回调onProcess中的buffers就是pcm格式的（16位），简单加个wav头就变成了wav文件。
> 
> 或者录制wav格式，录音结束得到的blob去掉wav头就可以了
> 
> https://github.com/xiangyuecn/Recorder/blob/646df8a8650ae3acad30ca9a9f29999ce94384c4/README.md#L364-L366
> 
> 也不知道你问的是不是这个😂

想请教下怎么加上wav头， 直接用Recorder.pcm2wav() 方法可以吗
