### ISSUE TITLE
每次点击录制都要弹框让我选择是否允许使用麦克风

### ISSUE THREAD

**Issue by Masquerades2015** [xiangyuecn/Recorder#48]
能不能只弹框一次?   包括微信端 pc端的浏览器

**Comment by xiangyuecn** [comment]
emmm... 有些浏览器是这样，没次请求权限都弹，不过大部分浏览器还好，只要确认过一次就不会弹了。

可以尽量open后一直保持着录音状态，不要close，这样多次录音就不会弹了；不过可能系统会提醒网页在后台偷偷录音一样；并且需要不同浏览器多多的测试兼容性，因为有些浏览器不close下次继续录音会有问题的（目前仅发现Safari有问题）。

**Comment by Masquerades2015** [comment]
> emmm... 有些浏览器是这样，没次请求权限都弹，不过大部分浏览器还好，只要确认过一次就不会弹了。
> 
> 可以尽量open后一直保持着录音状态，不要close，这样多次录音就不会弹了；不过可能系统会提醒网页在后台偷偷录音一样；并且需要不同浏览器多多的测试兼容性，因为有些浏览器不close下次继续录音会有问题的（目前仅发现Safari有问题）。

每次打开能不能只做一次请求权限, 即只执行一次getUserMedia , 一直保持对麦克风的使用状态, 但是录音开始和录音结束用start和close控制.

**Comment by xiangyuecn** [comment]
Recorder H5 提供了open和close，权限控制起来比较方便，应该不存在什么问题。

RecordApp只有1个权限控制的方法，检测完权限就关掉了，是对老弹权限请求的浏览器不友好，刚才已经对RecordApp 优化了一下，请求完权限后下一次开始录音不会再请求权限。稍微对那些不友好的浏览器友好了点

**Comment by Masquerades2015** [comment]
> Recorder H5 提供了open和close，权限控制起来比较方便，应该不存在什么问题。
> 
> RecordApp只有1个权限控制的方法，检测完权限就关掉了，是对老弹权限请求的浏览器不友好，刚才已经对RecordApp 优化了一下，请求完权限后下一次开始录音不会再请求权限。稍微对那些不友好的浏览器友好了点

非常感谢! 我已经看到了效果!
