### ISSUE TITLE
钉钉内置浏览器录制失败

### ISSUE THREAD

**Issue by pandashuai** [xiangyuecn/Recorder#49]
机型：小米8，
环境：钉钉（v4.7.6）内置浏览器，
失败提示原因：说没录音权限，但钉钉的所有权限已打开

![](https://res.pandashuai.com/tmp/微信图片_20190904120139.png)

![](https://res.pandashuai.com/tmp/微信图片_20190904120146.jpg)

**Comment by xiangyuecn** [comment]
感谢反馈，如果猜的没错，钉钉的浏览器也是UC内核，和支付宝一样，已知UC系内核虽然提供getUserMedia特性，但均不能录音。
