### ISSUE TITLE
建议start也加上回调函数

### ISSUE THREAD

**Issue by xumingjie1658** [xiangyuecn/Recorder#50]
在实际使用中发现，会概率性的出现”未开始录音“这个error，猜测是start的过程需要时间，而state置为1是在start所有工作做完之后才变化的，如果在state状态还没有变化的时候就执行stop的话，会有问题

**Comment by xumingjie1658** [comment]
createMediaStreamSource
media.connect(process);
process.connect(ctx.destination);
这些过程有没有可能耗时比较长，上面的原因也是一个分析，因为会概率性的出现未开始录音

**Comment by xiangyuecn** [comment]
😂原因不在月start，start是同步操作 (几乎是，AudioContext有个异步resume操作，不过可以忽略 很少会触发)，connect这些方法都是轻量级的。原因在于open操作是巨慢的。

一般写法是` open(function(){ start() })` 然后其他地方`stop()`，stop时如果检测了是否已open，就不会出现此问题了，但这不能阻止继续start。我写的demo里面没有做这个检测，也会出现这个问题，而且是比较严重的😂

加上回调也不能解决此问题，里面存着着复杂的异步环境，stop如果是为了关闭上次调用的start，但上次start并未开始执行，这就会很矛盾了。open和close也是同样的一个矛盾。

应该要想个办法给start和stop、open和close这两对方法加个锁，应该就能解决此问题。

**Comment by xumingjie1658** [comment]
open的速度是不是和操作系统的状态有关系？有时候刷新页面和重启浏览器都不能解决未开始录音的问题。我是ipad上的safari

**Comment by xumingjie1658** [comment]
这个问题出现的频率挺高的了，我的写法就是你上面说的一般写发。。一个按钮点击之后open并在回调函数里start，另外一个按钮负责stop，几乎每天都会报这个问题。因为我们的业务是一个录音页面一直开着，用户会一直在那个页面上反复的open start stop...

**Comment by xiangyuecn** [comment]
这确实是个问题，我研究一下看看怎么给start和stop加个互斥锁，open和close这对太复杂了

**Comment by xiangyuecn** [comment]
已更新recorder-core.js，demo里面的老毛病已经没有了。你这个问题的症状用新代码应该会有所减轻。

不过手速太快的话，确实open都没有完成就调用stop，start都没来得及调用那肯定还是会返回”未开始录音“

**Comment by xumingjie1658** [comment]
好的，我试试看:)
