### ISSUE TITLE
录制完语音后，播放倍率明显加快，导致录音时长变短

### ISSUE THREAD

**Issue by xinzikang** [xiangyuecn/Recorder#51]
录制设备：pc端chrome(版本ua[Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36])
录制格式：MP3
生成录音实例的options（使用默认设置）：var rec=Recorder();
问题描述：录制完成后，点击播放，会听到播放的语音速率明显加快。例如录制10秒的语音，播放 
                  的时候语速会加快，导致时长只有4秒。但是语音的内容并没有丢失。
出现频率：不稳定复现。但是有一定频率的出现。

**Comment by xiangyuecn** [comment]
[同一录音线上样本（mp3、webm）+复现样本.zip](https://github.com/xiangyuecn/Recorder/files/3669099/mp3.webm.%2B.zip)


已再现此问题，是由于电脑录音时太卡了，导致浏览器回调速率跟不上造成音频数据丢失，比如2秒录音只返回了1秒的数据，转码后就变成了1秒的录音。

实测发现cpu高负荷（其他进程大量占用cpu）的时候录音就是这种情况。目测低端手机上更容易出现此问题。。。解决方案慢慢研究
