### ISSUE TITLE
建议release不同版本，方便问题与版本控制

### ISSUE THREAD

**Issue by whalerain** [xiangyuecn/Recorder#54]

**Comment by xiangyuecn** [comment]
这个库里面目前没有一个版本号，因为开源之初没有考虑到这个问题，就拖到了现在这个样子。如果开发者仅仅是简单复制的源码，后期需要检测是否已更新的话确实比较麻烦。我后面在recorder-core里面增加了一个LM（LastModify）变量，记录的是文件更新时间（靠人工手动更新，经常会忘记去修改），方便快速对比源码是否需要更新。

如果是要再加release目测会大大的增加发布新代码的流程，没有版本号也不好怎么去发release😂

不过我个人还是蛮喜欢在使用github里面的代码的时候用commit记录的hash来当做版本号来使（README里面其他库的代码链接就是这个样子，稍微有利于更新和对比），因为很多库的版本号也是乱的一笔，这也是我当时只加LM不加Ver的一个影响因素。

**Comment by xiangyuecn** [comment]
已上传到了npm里面，也算是有了一点通常意义上的版本概念了，不过npm里面的版本号打算只更新patch部分（年月日6位+当日patch次数2位），以后代码更新后会同步提交到npm。

**Comment by xiangyuecn** [comment]
#60
