### ISSUE TITLE
发现一个时序问题

### ISSUE THREAD

**Issue by xumingjie1658** [xiangyuecn/Recorder#55]
mp3_complete执行的时候会给worker发送消息，在worker的回调里去触发stop的callback，然后执行mp3_stop，但是在我的应用里，worker的回调触发的比较慢，导致mp3_stop里面把ctx delete掉了，回调没法执行了．．

**Comment by xumingjie1658** [comment]
不知道是不是和我的应用里自己也使用了多个worker有关系．．

**Comment by xumingjie1658** [comment]
delete ctx是不是应该放到complete的onmessage的里面？

**Comment by xiangyuecn** [comment]
看了几遍都没能理解你的问题，这个ctx是什么？是mp3_start返回的startCtx吗

**Comment by xumingjie1658** [comment]
> 看了几遍都没能理解你的问题，这个ctx是什么？是mp3_start返回的startCtx吗
> 
> 像这种看起来比较复杂的问题，最好能贴点代码什么的，或者截图，就会比较好理解些

```
worker.onmessage=function(e){
				var ctx=openList[e.data.id];
				if(ctx){
					ctx.call&&ctx.call(e.data);
					ctx.call=null;
				};
			};
```
我看代码stop的True是这里被调用的，但是我们的情况是这个ctx不存在了，所以没有调到stop的True里面，我看了一下不存在的原因
```
Recorder.prototype.mp3_stop=function(startCtx){
	if(startCtx&&startCtx.worker){
		startCtx.worker.postMessage({
			action:"stop"
			,id:startCtx.id
		});
		startCtx.worker=null;
		delete openList[startCtx.id];
		
		//疑似泄露检测 排除id
		var opens=-1;
		for(var k in openList){
			opens++;
		};
		if(opens){
			console.warn("mp3 worker剩"+opens+"个在串行等待");
		};
	};
};
```
是这个mp3_stop的时候delete掉了。感觉设计的时候是想先调用onmessage再执行mp3_stop？在我这边的情况是先调用delete openList[startCtx.id]后调用var ctx=openList[e.data.id];了...

**Comment by xiangyuecn** [comment]
上面这些代码的调用顺序基本上是这样的：

``` sql
-> rec.stop()							#wait success callback
	-> rec.engineCtx.mp3_complete()				#wait mp3_complete callback
			-> worker.complete command execute	#wait worker onmessage
			
			#worker onmessage()
			#mp3_complete callback()
			
			#success callback() --最终结果回调
			-> rec._stop() --清理资源
			-> rec.engineCtx.mp3_stop()
			-> worker.stop command execute
			-> delete worker ctx
	
-> 其他同步执行的代码
```

Recorder里面调用stop方法后，rec.engineCtx.mp3_stop肯定是在worker onmessage回调后再执行的，如果没有onmessage回调是不可能执行到rec.engineCtx.mp3_stop方法（也就是Recorder内部的rec._stop方法），除非rec.stop没有完成就调用了rec.close清理了所有资源。

**Comment by xiangyuecn** [comment]
内部方法rec._stop存在两种情况被调用，一种是rec.stop完成录音、另一种是rec.close终止录音。你这个engineCtx.mp3_stop被提前调用，可能是你写的代码有问题，比如这种代码：
``` javascript
/********有问题的代码***************/
var rec=Recorder();rec.open(function(){rec.start();setTimeout(function(){
//--------------------------------

var worker=rec.engineCtx.worker;
worker.onmessageBak=worker.onmessageBak||worker.onmessage;
worker.onmessage=function(e){
	console.log("worker callback",e);
	worker.onmessageBak(e);
	console.log("已彻底结束");
};

rec.stop(function(){
	console.error("永远不会被调用 success，注释掉close就会显示")
},function(){
	console.error("永远不会被调用 fail，注释掉close就会显示")
});
console.log("等待stop结果")

rec.close();//这个调用和rec.stop同步执行，这种写法是错误的，应该把close放到stop回调里面

//---------------------------------
},1000);});
```

这个例子里面注释掉rec.close这行就正常了。

**Comment by xumingjie1658** [comment]
> 上面这些代码的调用顺序基本上是这样的：
> 
> ```sql
> -> rec.stop()							#wait success callback
> 	-> rec.engineCtx.mp3_complete()				#wait mp3_complete callback
> 			-> worker.complete command execute	#wait worker onmessage
> 			
> 			#worker onmessage()
> 			#mp3_complete callback()
> 			
> 			#success callback() --最终结果回调
> 			-> rec._stop() --清理资源
> 			-> rec.engineCtx.mp3_stop()
> 			-> worker.stop command execute
> 			-> delete worker ctx
> 	
> -> 其他同步执行的代码
> ```
> 
> Recorder里面调用stop方法后，rec.engineCtx.mp3_stop肯定是在worker onmessage回调后再执行的，如果没有onmessage回调是不可能执行到rec.engineCtx.mp3_stop方法（也就是Recorder内部的rec._stop方法），除非rec.stop没有完成就调用了rec.close清理了所有资源。

为啥我是先掉了mp3_stop再掉的onmessage，然后回调执行不了

**Comment by xumingjie1658** [comment]
> 内部方法rec._stop存在两种情况被调用，一种是rec.stop完成录音、另一种是rec.close终止录音。你这个engineCtx.mp3_stop被提前调用，可能是你写的代码有问题，比如这种代码：
> 
> ```js
> /********有问题的代码***************/
> var rec=Recorder();rec.open(function(){rec.start();setTimeout(function(){
> //--------------------------------
> 
> var worker=rec.engineCtx.worker;
> worker.onmessageBak=worker.onmessageBak||worker.onmessage;
> worker.onmessage=function(e){
> 	console.log("worker callback",e.data);
> 	worker.onmessageBak(e);
> 	console.log("已彻底结束");
> };
> 
> rec.stop(function(){
> 	console.error("永远不会被调用 success，注释掉close就会显示")
> },function(){
> 	console.error("永远不会被调用 fail，注释掉close就会显示")
> });
> console.log("等待stop结果")
> 
> rec.close();//这个调用和rec.stop同步执行，这种写法是错误的，应该把close放到stop回调里面
> 
> //---------------------------------
> },1000);});
> ```
> 
> 这个例子里面注释掉rec.close这行就正常了。

仔细看了一下，是我的写法错了
