### ISSUE TITLE
如何在录制过程中设置成静音

### ISSUE THREAD

**Issue by belier-cn** [xiangyuecn/Recorder#56]
看了一圈文档，没有发现相关api，那位大神指点一下，谢谢。

**Comment by xiangyuecn** [comment]
没有提供这种控制方法，自己在需要静音的时候把这个赋值改成0即为静音

https://github.com/xiangyuecn/Recorder/blob/1313c0f3b53cbe5a6a6e8f24e9fc2eb0d108498e/src/recorder-core.js#L97

**Comment by belier-cn** [comment]
好的，谢谢了，我试试看，有提供这样一个方法的想法么

**Comment by belier-cn** [comment]
经修改后打包，测试能静音
@xiangyuecn 谢谢了
