### ISSUE TITLE
ios webview内不支持

### ISSUE THREAD

**Issue by UWcan** [xiangyuecn/Recorder#57]
支持大部分已实现getUserMedia的移动端、PC端浏览器；主要包括：Chrome、Firefox、Safari、Android WebView、腾讯Android X5内核(QQ、微信)；不支持：UC系内核（典型的支付宝，大部分国产手机厂商的浏览器），**IOS上除Safari外的其他任何形式的浏览器（含PWA、WebClip、任何App内网页）**。

测试发现，页面在ios手机的app内访问，不能弹出授权弹窗。

**Comment by UWcan** [comment]
看错了，原来是写着不支持

**Comment by UWcan** [comment]
如果想在imo webview内支持录音，还有什么办法不？

**Comment by xiangyuecn** [comment]
既然都是app了，用原生的录音多简单。提供个接口给h5用，也很简单。

**Comment by UWcan** [comment]
> 既然都是app了，用原生的录音多简单。提供个接口给h5用，也很简单。
> 
> 参考 RecordApp，在app-support-sample目录内

嗯， 只能让客户端提供api了，不过这就涉及版本升级问题了，毕竟活动上线后，如果依靠app升级才能玩活动，产品们不乐意
