### ISSUE TITLE
大佬有考虑封装成npm包吗。

### ISSUE THREAD

**Issue by 1130204153** [xiangyuecn/Recorder#60]

**Comment by 1130204153** [comment]
公司最近让我做这个，ios兼容搞的我头疼，是react项目，想引你这个插件，有什么简单的办法引进来呢？

**Comment by xiangyuecn** [comment]
不清楚搞成react的库需要编写成什么样的风格，把代码copy过去当做自己写的代码来对待应该很容易引入。

精力有限目前不打算把代码改成特定风格传到npm。

**Comment by xiangyuecn** [comment]
刚入门vue，已经把这个库微调了一下支持import导入了，npm现学现卖已经发布上去了😄

#9 #17 #38
