### ISSUE TITLE
能够提供原始流的配置吗

### ISSUE THREAD

**Issue by 1130204153** [xiangyuecn/Recorder#61]
公司用的讯飞的实时语音，希望在实时发送语音的例子中提供一个返回原始音频流的配置，方便进一步的处理，转换成我们想要的格式

**Comment by xiangyuecn** [comment]
Recorder初始化的set中添加onProcess回调即可得到原始的pcm数据流

**Comment by 1130204153** [comment]
我指的不是pcm数据流，就是最原始的，没有经过任何转码的流，有提供这个配置吗

**Comment by xiangyuecn** [comment]
回调得到的是原始 Float32Array 转成的 Int16Array，如果你要最最原始的Float32Array，修改此处代码，e.inputBuffer就是浏览器提供的原始Float32Array pcm数据

https://github.com/xiangyuecn/Recorder/blob/5c1c836b11887fed92ae2612af8d616f5adf4998/src/recorder-core.js#L94-L104

**Comment by xiangyuecn** [comment]
可以把100行开始以下的代码全部替换成你自己的

**Comment by 1130204153** [comment]
好的，谢谢大佬了啊

**Comment by Jackie-Tang** [comment]
> 好的，谢谢大佬了啊

你这个是怎么改的？

**Comment by Jackie-Tang** [comment]
> 回调得到的是原始 Float32Array 转成的 Int16Array，如果你要最最原始的Float32Array，修改此处代码，e.inputBuffer就是浏览器提供的原始Float32Array pcm数据
> 
> https://github.com/xiangyuecn/Recorder/blob/5c1c836b11887fed92ae2612af8d616f5adf4998/src/recorder-core.js#L94-L104

现在有提供直接获取的途径么？
