### ISSUE TITLE
Recorder.mock存在一个bug

### ISSUE THREAD

**Issue by JS-Hao** [xiangyuecn/Recorder#62]
问题：Recorder.mock + stop配合生成一个新音频blob时存在问题
详情：示例代码如下图所示，当使用Recorder.mock + stop，将一个pcm数据转成音频时，会报”生成的mp3无效“的错误异常
```javascript
new Recorder({type: 'mp3'})
  .mock(pcmData, srcSampleRate)
  .stop(function(blob, duration) {
    console.log('生成的blob', blob, duration)
})
```

当我看了源码后发现，如果把mock函数内部的**pcmData**赋值方式进行小修改，就能转换成功了（如下图所示，不要将pcmData包裹在一个新数组内）
```javascript
mock:function(pcmData,pcmSampleRate){
  var This=this;
  This._stop();//清理掉已有的资源
		
  This.isMock=1;
  // before
  // This.buffers = [pcmData];
  // after
  This.buffers=pcmData;
  This.recSize=pcmData.length;
  This.srcSampleRate=pcmSampleRate;
    return This;
}
```

**Comment by xiangyuecn** [comment]
mock的pcm参数是一维数组 [Int16,...]，你应该是传的一个二维数组，被当成了[0]导致最终生成的mp3文件大小异常。

如果你要传二维的进来，可以用Recorder.SampleData转成一维的，或者自己把二维展开成一维。

综上，这不是bug，是feature。😁
