### ISSUE TITLE
如何实现边录音边上传,每60s上传一次录音

### ISSUE THREAD

**Issue by kxy1107** [xiangyuecn/Recorder#64]
想要实现录音一直录着，但是每隔60s将录好的音频上传到服务器去，也就是分片上传，第一次传0-60s的mp3数据，第二次传60-120s的数据。目前采用的是每隔60s停止录音stop，在开启start，但是会出现衔接会有问题。。想通过Recorder的onProcess回调去实现，但是不知道具体要怎么实现将其中的一端buffer转成mp3

**Comment by xiangyuecn** [comment]
参考demo中的例子 [【教程】实时转码并上传](https://xiangyuecn.github.io/Recorder/assets/%E5%B7%A5%E5%85%B7-%E4%BB%A3%E7%A0%81%E8%BF%90%E8%A1%8C%E5%92%8C%E9%9D%99%E6%80%81%E5%88%86%E5%8F%91Runtime.html?jsname=teach.realtime.encode_transfer)，点这个链接测试，把里面的间隔修改成你需要的间隔，就能达到目的

https://github.com/xiangyuecn/Recorder/blob/11b0420befba6fce57a76239dd7ceaafb4cbcd8b/assets/runtime-codes/teach.realtime.encode_transfer.js#L18

核心代码，主要就是用到Recorder.SampleData，mock两个方法
https://github.com/xiangyuecn/Recorder/blob/11b0420befba6fce57a76239dd7ceaafb4cbcd8b/assets/runtime-codes/teach.realtime.encode_transfer.js#L51-L94

**Comment by kxy1107** [comment]
感谢你的回答，我这边目前是可以实现功能，但是录音效果不太理想，不管是插着耳机录还是在封闭环境下外放音频录音质都有点差。不清楚是不是什么参数设置有问题 。目前我设置的参数
------open的时候
`rec = Recorder({
      type: "mp3",
      bitRate: 16,
      sampleRate: 16000,
      onProcess: function (buffers, powerLevel, bufferDuration, bufferSampleRate) {
        that.onrecorderProcess(buffers, powerLevel, bufferDuration, bufferSampleRate)
      }
    });`
----onrecorderProcess回调处理
`onrecorderProcess(buffers, powerLevel, bufferDuration, bufferSampleRate) {

      let time = Math.floor(bufferDuration / 1000);
      if (bufferDuration > 0 && time % 60 == 0 && curRecoderTime != time) {
        console.log('-----recorderProcess----')
        console.log(buffers)
        console.log(powerLevel, bufferSampleRate)
        console.log(bufferDuration)
        curRecoderTime = time;
        if (this.recordAllTime < 600) {
          this.transMp3(false)
        }
      }
    },`
----转mp3
`transMp3(isClose) {
      let that = this;
      let testSampleRate = 16000;
      let testBitRate = 16;
      let realTimeSendTryType = 'mp3';
      //借用SampleData函数进行数据的连续处理，采样率转换是顺带的
      let chunk = Recorder.SampleData(rec.buffers, rec.srcSampleRate, testSampleRate, realTimeSendTryChunk, { frameType: isClose ? "" : realTimeSendTryType });
      console.log('-----chunk----')
      console.log(chunk)
      //清理已处理完的缓冲数据，释放内存以支持长时间录音，最后完成录音时不能调用stop，因为数据已经被清掉了
      for (var i = realTimeSendTryChunk ? realTimeSendTryChunk.index : 0; i < chunk.index; i++) {
        rec.buffers[i] = null;
      }
      realTimeSendTryChunk = chunk;
      //没有新数据，或结束时的数据量太小，不能进行mock转码
      if (chunk.data.length == 0 || isClose && chunk.data.length < 2000) {
        return;
      }
      //通过mock方法实时转码成mp3、wav
      var recMock = Recorder({
        type: realTimeSendTryType
        , sampleRate: testSampleRate //采样率
        , bitRate: testBitRate //比特率
      });
      recMock.mock(chunk.data, chunk.sampleRate);
      recMock.stop(function (blob, duration) {
        console.log('转码mp3成功-------')
        console.log(blob, duration)
        let res = {
          "blob": blob,
          "duration": duration
        }
        if (duration > 1) {
         //上传到服务器
          that.uploadAudioFile(res,)
        }
        if (isClose) {
          realTimeSendTryChunk = null;
          that.recordAllTime = 0;
          rec.close();//释放录音资源
        }
        //转码好就推入传输
      }, function () {
      });
    },`

**Comment by xiangyuecn** [comment]
16kbps 16000hz就是低品质的语音，要清晰点的就把transMp3里面这两个提高点 48000hz+32kbps，Recorder初始化type用unknown类型
