### ISSUE TITLE
如何实现把某段时间录音为静音？

### ISSUE THREAD

**Issue by hgt803** [xiangyuecn/Recorder#65]
rt

**Comment by xiangyuecn** [comment]
在需要静音的时候，把这个地方的赋值改成0即可，自行修改源码

https://github.com/xiangyuecn/Recorder/blob/fd047f20cc3b2e7be2919a81a8513175101e598b/src/recorder-core.js#L108

**Comment by xiangyuecn** [comment]
#56

**Comment by hgt803** [comment]
谢谢大佬

**Comment by hgt803** [comment]
源码经常更新，把直接修改源码无法及时更新。希望大佬能添加这个功能

**Comment by xiangyuecn** [comment]
有道理，其实在onProcess里面也可以进行此处理，直接修改buffers数组数据。不过对支持边录边转的格式不太友好，我待会改动一下core源码

**Comment by xiangyuecn** [comment]
已发布新版本，现在可以在onProcess中直接修改buffers，把需要静音的buffer内容全部替换成0即可。这样也免去了改动源码

代码参考:
``` javascript
var processIdx=0,isMute=true;

......

onProcess:function(buffers){
	if(isMute){
		for(;processIdx<buffers.length;processIdx++){
			var buffer=buffers[processIdx];
			for(var i=0;i<buffer.length;i++){
				buffer[i]=0; //置为0即可静音
			};
		};
	};
}
```
