### ISSUE TITLE
13.3版本的ipad无法录音，不支持getUserMedia

### ISSUE THREAD

**Issue by GeniusCyberpunk** [xiangyuecn/Recorder#66]

**Comment by GeniusCyberpunk** [comment]
12.4版本的iphone也无法录音，不支持getUserMedia

**Comment by xiangyuecn** [comment]
ios上只有Safari能进行h5录音，其他任何浏览器（含app内置）都不能进行h5录音，是苹果的限制

**Comment by GeniusCyberpunk** [comment]
我使用的是微信客户端加载的H5界面，它默认的支撑的应该是Safari浏览器吧？还是说会是软件版本的问题吗？

**Comment by GeniusCyberpunk** [comment]
经测试，Safari浏览器支持h5录音，微信客户端内置浏览器不能支持h5录音。
