### ISSUE TITLE
recorderAPP.Stop()失效

### ISSUE THREAD

**Issue by WDRocs** [xiangyuecn/Recorder#67]
ios微信上录音使用setInterval计时，大于等于两分钟自动调用Stop方法，未触发，既没有走success，也没有走err，不是一定会出现，不超出一分钟不会出现此问题

**Comment by WDRocs** [comment]
后续发现报错uploadVoice:missing arguments

**Comment by xiangyuecn** [comment]
这样就麻烦了，难处理这种bug，如果下面代码控制台输出的localId确实是undefined，那么要么是wx.startRecord返回了不正常的数据，要么是wx.onVoiceRecordEnd返回了不正常的数据。

https://github.com/xiangyuecn/Recorder/blob/fbefe7715bc30e198aa897ba4b7b879175bf65c7/src/app-support/app-ios-weixin-support.js#L296

如果是最后一段录音导致的问题，比如本应该出现两段录音但出现了3段，这样的我们稍微好处理，把这个地方源码调大点

https://github.com/xiangyuecn/Recorder/blob/fbefe7715bc30e198aa897ba4b7b879175bf65c7/src/app-support/app-ios-weixin-support.js#L322

如果是其他原因的话难搞哦

**Comment by xiangyuecn** [comment]
这个问题是解决了吗？

**Comment by WDRocs** [comment]
最后把时间限制改了一下，不是整分钟数了，确实好像是因为自动监听那里出现了不正常的数据

**Comment by xiangyuecn** [comment]
👌我昨晚也再现了这个问题，定时一分钟整也会出现，看样子是onVoiceRecordEnd里面导致的问题，晚点干掉这个bug

**Comment by xiangyuecn** [comment]
此问题已修复，新代码测试没有再出现这个问题，新代码控制台日志打的也更清楚些
