### ISSUE TITLE
amr转wav时间被拉长

### ISSUE THREAD

**Issue by WDRocs** [xiangyuecn/Recorder#68]
微信中录音一分三十秒，最后由amr转换为wav格式，Stop方法给出的音频时长变为两分三十秒，测试发现一分十五秒转完格式之后的时间是正常的，没有很大出入，录音时间好像有一个节点，超出就会被拉长，不超出就没关系，很迷幻

**Comment by xiangyuecn** [comment]
测试定时90000ms自动停止录音，没有再现这个问题。你那是必现吗？贴一下会出问题的调用代码就更好了

**Comment by WDRocs** [comment]
最后证明是我的方法用错了。。。难搞
