### ISSUE TITLE
ios微信里权限请求没有回调

### ISSUE THREAD

**Issue by WDRocs** [xiangyuecn/Recorder#69]
RecorderAPP.RequestPermission方法调用有的时候不会有回调，根据测试观察，是每第一次进入页面会这样，没有看到报错，每次清理微信缓存后都会出现，第二次进入表现正常

**Comment by xiangyuecn** [comment]
是因为网速慢吧，估计是还在Install，IOS微信里面会自动加载amr解码器，如果不是引用的压缩版的，这个文件巨大，加载巨慢

**Comment by WDRocs** [comment]
npm引入是不是就没有优化空间了

**Comment by WDRocs** [comment]
换了压缩版本试了试，还是会出现这个问题，ios微信真的不太适合录音

**Comment by xiangyuecn** [comment]
确定Install完成了吗？

**Comment by WDRocs** [comment]
不确定

**Comment by xiangyuecn** [comment]
那可能是还在Install，没有完成时所有权限请求都会被推后到完成时处理

**Comment by xiangyuecn** [comment]
你可以直接把所有需要的js手动进行引入，这样RecordApp就不会去自动加载js库了，会快些和稳定些

**Comment by OneCoin5759** [comment]
IOS微信直接提示，打开录音失败：此浏览器不支持录音

**Comment by lixianghong66** [comment]
IOS微信直接提示，打开录音失败：此浏览器不支持录音

**Comment by xiangyuecn** [comment]
用特殊兼容版 RecordApp： https://github.com/xiangyuecn/Recorder/tree/master/app-support-sample
