### ISSUE TITLE
Safari上不支持连续录音

### ISSUE THREAD

**Issue by funfang** [xiangyuecn/Recorder#7]
点击打开录音后，点击录制，然后点击停止，播放音频正常。再次点击录制，然后点击停止，播放音频没声音，Chrome上没这个问题。

**Comment by xiangyuecn** [comment]
有时间我研究一下。您那有没有调试出是哪里的问题，或者已有什么解决方案？

**Comment by funfang** [comment]
没有，好像是safari的问题，我试了很多的库，都有这个问题。

**Comment by Haok9800** [comment]
你好， 现在我也有个类似的库，我调用的方法和您的是一样Navigator.getUserMedia()，但是有些IOS最新版本对此不兼容。目前MDN规范是 navigator.mediaDevices.getUserMedia(constraints)，是不是最新版本safari浏览器遗弃了废旧的方法。

**Comment by xiangyuecn** [comment]
我用的是兼容写法，只会出现两种情况：要么是支持，要么是不支持。IOS上出现第三种情况那甩锅给苹果，妥妥的，哈

https://github.com/xiangyuecn/Recorder/blob/977760f4e460d49f40aa292d193dae995ce30ddd/src/recorder-core.js#L36-L42

**Comment by Haok9800** [comment]
是的，现在有用户反应ios12的版本不支持录音，我用的也是兼容写法。但是11和10的版本可以用，唉，愁死了。
