### ISSUE TITLE
电脑上Microsoft Edge浏览器不能录音

### ISSUE THREAD

**Issue by chenguozhi00** [xiangyuecn/Recorder#71]
录音结束一直显示正在编码mp3...

**Comment by xiangyuecn** [comment]
在线demo也是这个情况吗？ edge啥版本呢？

**Comment by chenguozhi00** [comment]
在线demo录制完就显示正在编码mp3...，然后就没反应了，版本是Microsoft Edge 44.18362.449.0，Microsoft EdgeHTML 18.18363

**Comment by xiangyuecn** [comment]
太惨了，只下了chromium内核的最新版edge，没有这个版本的edge，测试不了😂
