### ISSUE TITLE
IOS微信直接提示，打开录音失败：此浏览器不支持录音

### ISSUE THREAD

**Issue by OneCoin5759** [xiangyuecn/Recorder#77]
IOS微信直接提示，打开录音失败：此浏览器不支持录音

**Comment by xiangyuecn** [comment]
阅读文档开头第一段话。ios 上除了Safari外，没有一个浏览器可以H5录音。

微信里面倒还好，可以用微信的jssdk录音，参考RecordApp

**Comment by OneCoin5759** [comment]
OK
