### ISSUE TITLE
webpack-vue-uniapp打包后，mp3.js报错_parseInt2 is not defined，beta-amr-engine.js报错Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by yaoxin2017** [xiangyuecn/Recorder#79]
在uniapp里使用该项目时，控制台出现错误log：
beta-amr-engine.js:451 Uncaught TypeError: Cannot read property 'slice' of null
    at parseJSFunc (beta-amr-engine.js:451)
    at beta-amr-engine.js:458
    at beta-amr-engine.js:400
    at Object.../../../../../11.workspace/vueWorkSpace/supervisorUniApp/recorder-core/src/engine/beta-amr-engine.js (beta-amr-engine.js:8)
    at __webpack_require__ (bootstrap:766)
    at fn (bootstrap:129)
    at Object.../../../../../11.workspace/vueWorkSpace/supervisorUniApp/main.js (main.js:14)
    at __webpack_require__ (bootstrap:766)
    at fn (bootstrap:129)
    at Object.0 (log.js:47)

我查了这行代码 451行是这个：var parsed = jsfunc.toString().match(sourceRegex).slice(1);

求教怎么处理？

以下是我使用方式，使用nmp下载源码后，源码位于node_modules目录下，我将recorder-core（以及该文件夹的内部文件）复制到 我的uniapp项目跟目录，并在main.js中引入（如下import所示），这时在控制台就会出现 上面的 错误log，显示 beta-amr-engine 的451行报错。

import RecordApp from 'recorder-core/src/app-support/app'
import 'recorder-core'
import 'recorder-core/src/engine/mp3'
import 'recorder-core/src/engine/mp3-engine'
//ios 微信支持
import 'recorder-core/src/app-support/app-ios-weixin-support'
import 'recorder-core/ios-weixin-config.js'
import 'recorder-core/src/engine/beta-amr'
import 'recorder-core/src/engine/beta-amr-engine'

**Comment by xiangyuecn** [comment]
参考： 
https://github.com/BenzLeung/benz-amr-recorder/issues/17
https://github.com/BenzLeung/benz-amr-recorder/issues/9

晚点我尝试更新一下beta-amr-engine这个文件

**Comment by yaoxin2017** [comment]
感谢作者的回复。

现在有个新问题，就是我暂时去掉了ios微信录音的支持，此时没有报错了。
但是在录音时有了新的错误： Uncaught ReferenceError: _parseInt2 is not defined

源码里没有_parseInt2 ，通过浏览器控制台查看对应的是 源码的parseInt，我截图了，麻烦看下

[报错详情的截图.zip](https://github.com/xiangyuecn/Recorder/files/4381782/default.zip)

**Comment by yaoxin2017** [comment]
补充一下，目前依赖如下：

import Recorder from 'recorder-core'
import 'recorder-core/src/engine/mp3'
import 'recorder-core/src/engine/mp3-engine'

**Comment by xiangyuecn** [comment]
#78

**Comment by xiangyuecn** [comment]
看起来像是babel给js代码加料（投毒）了。麻烦发一下你的webpack配置（发一份能在现问题的源码就更好了，你看看能不能新建一个能一样产生问题的简单demo）

**Comment by xiangyuecn** [comment]
beta-amr-engine这个文件我看了一下benz-amr-recorder的作者只更新了一次
https://github.com/BenzLeung/benz-amr-recorder/commit/f791056bbfe3c378255de6b2265f3a160ce2b2e9
我看了一下他的变更，改动的代码并没有任何实际的作用，虽然抑制住了null，但并没有解决根源性的问题，新版本不匹配直接退出不知道会不会产生新的bug。sourceRegex的老版本匹配范围包含了新版本的匹配范围，新版本能匹配到范围反而更小了。以前他更新的时候我就检查过代码，所以不会把beta-amr-engine更新到他的新版本。

我怀疑你那编译出来的js函数变成 function xxx(){}这种形式，导致sourceRegex不能匹配。就跟parseInt一样，被改写成了别的函数

**Comment by yaoxin2017** [comment]
我用的是DCloud的HbuilderX开发工具（ 官网：https://www.dcloud.io/ ）      这个开发工具新建uniapp项目里面没有像vue-cli那样有详细的配置文件，HbuilderX虽然也是用webpack打包，但是把一些细节封装隐藏起来了

**Comment by xiangyuecn** [comment]
你那试试把下面两个地方的 `parseInt`改成 `window.parseInt` 试试看还会不会被编译成_parseInt2，如果都正常了那我就把库里的源码更新一下

https://github.com/xiangyuecn/Recorder/blob/6dd3e961558a6585f1e4f8d3d5c5d74bbc842bd9/src/engine/mp3.js#L254-L258

**Comment by yaoxin2017** [comment]
改后报错：
8b4c30ae-b819-40de-948c-61eb39e10ed1:14221 Uncaught ReferenceError: window is not defined
    at Object.rm (8b4c30ae-b819-40de-948c-61eb39e10ed1:14221)
    at Object.fn (8b4c30ae-b819-40de-948c-61eb39e10ed1:14268)
    at onmsg (8b4c30ae-b819-40de-948c-61eb39e10ed1:14190)

**Comment by yaoxin2017** [comment]
[recorder.zip](https://github.com/xiangyuecn/Recorder/files/4384826/recorder.zip)
  这个是uniapp项目，里面只集成了 该录音库，解压后用Hbuilder打开就行了，打开后在开发工具右边点击  预览 就会自动编译运行了，浏览器 用 http://localhost:8080/#/  也可以打开，点击录音在浏览器控制台就可以看到错误信息了

**Comment by xiangyuecn** [comment]
https://github.com/xiangyuecn/Recorder/commit/dd1aafb93683f6a0553984a4b6dd94b29b9c685b 两个问题都已修复。

beta-amr-engine里面这段jsfunc的分解代码其实压根一点用处都没有，最外面这层函数没有地方用到了，直接剔除了这段带有隐患的源码。

parseInt应该是babel-polyfill中配置的原因，Hbuilder的锅，应该是配置了对parseInt、parseFloat的处理（全局下的parseInt又没有说会废弃，毛用处都没有，不像Promise还有点卵用这种）😂

**Comment by yaoxin2017** [comment]
感谢作者！已在uniapp上实测，问题已解决。
