### ISSUE TITLE
Android app中打开貌似不支持？

### ISSUE THREAD

**Issue by somonus** [xiangyuecn/Recorder#8]
提示未授权

**Comment by xiangyuecn** [comment]
安卓应用？webview？

不理解你说的啥问题，如果是webview应该是需要WebChromeClient里override onPermissionRequest吧。（有点不搭边）

**Comment by somonus** [comment]
是Android的webview打开，用你的示例打开时提示的是用户拒绝录音权限，我自己实现的页面走到了error的callback里面   不过error是空的

**Comment by xiangyuecn** [comment]
onPermissionRequest里给授权，webview基本上所有涉及到的权限好像都需要自己实现，并不像浏览器自带实现了弹框确认

**Comment by hanqingqingmomo** [comment]
我怎么实现了这方法 还是得不到权限

**Comment by xiangyuecn** [comment]
@hanqingqingmomo 试试我写的测试apk .assets/android_test/app-debug-xxx.apk
