### ISSUE TITLE
浏览器没有关闭麦克风权限的时候，无法在rec.open的失败回调获取到

### ISSUE THREAD

**Issue by z-lionel** [xiangyuecn/Recorder#80]
如题所示，
然后在谷歌浏览器会报错 DOMException: Permission denied，

Traffic Analysis Image: Recorder.TrafficImgUrl=//ia.51.la/go1?id=20469973&pvFlag=1

如何正确捕捉到错误，在失败回调里面可以正常提示

**Comment by xiangyuecn** [comment]
能提供一个精简版的可以复现这个问题的代码吗？还有浏览器的UserAgent提供一下😊

Permission denied 这个是拒绝了录音权限，应该会走open的fail回调，难道是和火狐一样存在忽略权限请求功能？

**Comment by z-lionel** [comment]
> 能提供一个精简版的可以复现这个问题的代码吗？还有浏览器的UserAgent提供一下😊
> 
> Permission denied 这个是拒绝了录音权限，应该会走open的fail回调，难道是和火狐一样存在忽略权限请求功能？

不好意思，应该是描述有点问题，是谷歌浏览器我手动点了拒绝麦克风权限，然后，调用open的时候，fail并没有回调出事件

**Comment by xiangyuecn** [comment]
升级了一下chrome，麦克风权限设置为询问后试了一下拒绝，能正常收到fail回调

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36

**Comment by z-lionel** [comment]
> 升级了一下chrome，麦克风权限设置为询问后试了一下拒绝，能正常收到fail回调
> 
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36

不好意思，后来测试了下可以，我自己监听回调的事件名写错了，谢谢了
