### ISSUE TITLE
使用demo，运行scratch编辑器，不提示录音权限

### ISSUE THREAD

**Issue by ali0201** [xiangyuecn/Recorder#81]
url: `https://scratch.mit.edu/projects/editor/?tutorial=getStarted`

但是这个网址在Safari上，是ok的。因为项目需要，要在iPad或iPhone上运行。

谢谢。

步骤：

1. 
![image](https://user-images.githubusercontent.com/7078700/79551445-40f98700-80cc-11ea-9121-03294e31e8e9.png)

2. 
![image](https://user-images.githubusercontent.com/7078700/79551486-4ce54900-80cc-11ea-8684-9c30a7435c59.png)

**Comment by xiangyuecn** [comment]
你这个里面的录音和这个GitHub项目没有关系吧😂 如果mac safari里面能录，ios里面safari不能录，说明他们获取录音功能的那段代码兼容性不好，自己研究源码改改兼容性

**Comment by ali0201** [comment]
> 你这个里面的录音和这个GitHub项目没有关系吧😂 如果mac safari里面能录，ios里面safari不能录，说明他们获取录音功能的那段代码兼容性不好，自己研究源码改改兼容性

😅嗯嗯，iOS Safari里也是能录的，找了很多资料。找到你这里，就想向你请教一下。

**Comment by xiangyuecn** [comment]
嗯，录音在现代浏览器上的兼容性还可以，唯独在ios系统里面除外

**Comment by ali0201** [comment]
> 嗯，录音在现代浏览器上的兼容性还可以，唯独在ios系统里面除外

谢谢。我也找了很多资料，说对`wkwebview`和`webView`不支持。我再找找资料研究吧😅
