### ISSUE TITLE
初始化recorder  报错  按照demo写的，size of undefined

### ISSUE THREAD

**Issue by SuiFengErQu** [xiangyuecn/Recorder#82]
vue.esm.js?efeb:1897 TypeError: Cannot set property 'size' of undefined
    at t (recorder.js?bf08:11)
    at e (recorder.js?bf08:11)

**Comment by xiangyuecn** [comment]
编译器加料了吧，如果搞不定就直接通过script标签引入吧，不走编译环节

**Comment by SuiFengErQu** [comment]
好的，这个recorder可以再ios手机上用吗，就是打包成app的话，是不是可以获取手机的麦克风权限，实现录音，我看好多是指兼容浏览器的

**Comment by xiangyuecn** [comment]
ios app里面只能h5调用app原生接口录音，ios里面纯粹的h5除了Safari，任何app都没法仅靠h5来录音。参考RecordApp

**Comment by SuiFengErQu** [comment]
明白了
