### ISSUE TITLE
加入waveview后无法手动停止录音，报错未开始录音

### ISSUE THREAD

**Issue by hideinheart** [xiangyuecn/Recorder#83]
不加waveview时候一切正常，只用到了最基本的open、start、stop；
另外即使是添加了waveview相关，在recstart()方法里用settimeout调用的stop方法可以正常调用执行，没有报错；
但是添加waveview相关语句后无法手动停止录音，console结果是[xxxxxxxxxxxx]stop 2290ms 补0ms，看这个输出应该是录音成功了，是不是哪里判断条件写错了呢？我找了下这个输出语句是写在if(isMock)判断里的，上下文找了一下，不太明白这个isMock是代表什么，望作者解惑

**Comment by xiangyuecn** [comment]
你哪里魔改乱了吧。一般去用这个库，不需要关注isMock这些代码，这个玩意是给转码、RecordApp等用的

**Comment by hideinheart** [comment]
> 你哪里魔改乱了吧。一般去用这个库，不需要关注isMock这些代码，这个玩意是给转码、RecordApp等用的

我完全没改啊，就是因为一直报错才去看的源代码，调用也都是按你教程那里写的来，不晓得为什么会这样

**Comment by hideinheart** [comment]
> 你哪里魔改乱了吧。一般去用这个库，不需要关注isMock这些代码，这个玩意是给转码、RecordApp等用的

我又试了好多次，有的时候可以手动停止，大部分时候都会报错，另外问一下open之后第一次开始start也会输出ctx resume吗，我没有暂停啊

**Comment by xiangyuecn** [comment]
- 测试在线quickstart demo，看看是否也有同样问题
- copy quickstart改改放到网站里面用
- 还不行把代码贴出来

**Comment by sanjiu81** [comment]
我的理解是那个wave在open里绘制的，每次start之前都要open初始化一下（如果不close释放资源）
