### ISSUE TITLE
使用flutter的webview官方插件打开提示：打开失败，用户拒绝了录音权限

### ISSUE THREAD

**Issue by zhou-zc** [xiangyuecn/Recorder#87]

**Comment by xiangyuecn** [comment]
Android这个要原生代码处理onPermissionRequest请求，不知道flutter的插件到底处理了没有，要自己去研究一下他们的文档。

ios没戏，要自己用原生实现一套录音接口给h5调用

**Comment by woSihaizi** [comment]
> Android这个要原生代码处理onPermissionRequest请求，不知道flutter的插件到底处理了没有，要自己去研究一下他们的文档。
> 
> ios没戏，要自己用原生实现一套录音接口给h5调用

处理了onPermissionRequest请求，开通了录音权限，还是录音不成是什么原因

**Comment by zhou-zc** [comment]
我这面集成x5的内核是没问题的。正常使用中。。。

**Comment by woSihaizi** [comment]
> 我这面集成x5的内核是没问题的。正常使用中。。。

请问是在哪里调用的onPermissionRequest，我现在是在rec.open（）没有录音权限中使用

**Comment by zhou-zc** [comment]
我之前遇到的问题是集成了flutter的webview插件无法使用录音，然后就自己写了x5的插件并重写onPermissionRequest问题就得到了解决。

**Comment by woSihaizi** [comment]
> 我之前遇到的问题是集成了flutter的webview插件无法使用录音，然后就自己写了x5的插件并重写onPermissionRequest问题就得到了解决。

只开通了onPermissionRequest允许录音权限，还需要写x5插件嘛，写x5的插件的目的是解决什么

**Comment by zhou-zc** [comment]
写x5插件解决一些网页的兼容性问题。我们项目中的一些表单在某些手机上显示白屏，集成x5很好的解决了这个问题，当然也包括录音的问题。你遇到的问题可能和我不太一样吧。你可以试一下你的网页在QQ或者微信里面打开是否可以录音

**Comment by woSihaizi** [comment]
> 写x5插件解决一些网页的兼容性问题。我们项目中的一些表单在某些手机上显示白屏，集成x5很好的解决了这个问题，当然也包括录音的问题。你遇到的问题可能和我不太一样吧。你可以试一下你的网页在QQ或者微信里面打开是否可以录音

在微信或者浏览器可以正常录音，苹果手机也正常，就是在app里安卓手机提示用户拒绝了录音授权，已经写了onPermissionRequest，请求了app的录音权限允许录音了，还是提示拒绝录音授权呢，还有可能是哪里的问题嘛

**Comment by zhou-zc** [comment]
可以把onPermissionRequest方法的代码提上来看看

**Comment by woSihaizi** [comment]
> 可以把onPermissionRequest方法的代码提上来看看

插件里的webview需要开启录音权限嘛
