### ISSUE TITLE
请问，为什么非要https下才能用呢？

### ISSUE THREAD

**Issue by cliveyuan** [xiangyuecn/Recorder#88]
为什么非要https下才能用呢？

**Comment by xiangyuecn** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Privacy_and_security

**Comment by zhuzhh** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Privacy_and_security

如何本地开发调试呀？谢谢

**Comment by xiangyuecn** [comment]
@zhuzhh 本地开发也一样配一个ssl证书，用一个测试域名解析到局域网的电脑ip就OK了，这样是最简单的

**Comment by zhuzhh** [comment]
> @zhuzhh 本地开发也一样配一个ssl证书，用一个测试域名解析到局域网的电脑ip就OK了，这样是最简单的

我用vue-cli起得项目，支持 https 参数，启动项目时携带 --https 就可以了，感谢

**Comment by sanjiu81** [comment]
启动项目时携带--https，这个是怎么操作的啊？
