### ISSUE TITLE
微信浏览器不支持录音

### ISSUE THREAD

**Issue by augustdai** [xiangyuecn/Recorder#89]
微信浏览器、平静浏览器不支持录音，微信、谷歌都是最新版本。

**Comment by xiangyuecn** [comment]
到在线测试页面里面测试看看，IOS用RecordApp测试。然后把不能录音的浏览器的UA发一下，测试页面底下有提供

**Comment by augustdai** [comment]
不支持，只要把连接发到微信里测试一下就看到了，不支持此浏览器。

**Comment by xiangyuecn** [comment]
https://github.com/xiangyuecn/Recorder/tree/master/app-support-sample
