### ISSUE TITLE
能否支持npm的方式引入

### ISSUE THREAD

**Issue by xumingjie1658** [xiangyuecn/Recorder#9]
能否支持npm的方式引入

**Comment by xiangyuecn** [comment]
目前没有这个打算，主要是对npm不熟:joy:
这个类库已经有一定的模块化基础，应该稍微加点代码就能支持CommonJS、AMD规范，有没有兴趣参与把这个库改造成npm包和发布？

**Comment by xumingjie1658** [comment]
尴尬了，有时间我可以参与搞搞

**Comment by xiangyuecn** [comment]
已上传到了npm，通过 `npm i recorder-core` 使用。和clone源码使用区别不大
