### ISSUE TITLE
报错：录音失败:未加载mp3编码器

### ISSUE THREAD

**Issue by yuenlin** [xiangyuecn/Recorder#90]
![image](https://user-images.githubusercontent.com/38040365/84482162-d2026e00-acc9-11ea-9363-ba4912cdb78d.png)
如图所示，js我全部都引入了，但是启动一直报错：录音失败:未加载mp3编码器
![image](https://user-images.githubusercontent.com/38040365/84482215-e8a8c500-acc9-11ea-8838-9d9b7f18458f.png)

**Comment by yuenlin** [comment]
我从 快速使用 中，没有找到相关的加载编码器的方法。

**Comment by yuenlin** [comment]
我从代码里直接下载的jar包会报错，用cdn地址引入的就不会报错了。

**Comment by xiangyuecn** [comment]
按1、2、3 顺序加载不同性质的js，一定要把recorder-*.js放到最前面，不然挂载的其他其他编码器插件会被覆盖

https://github.com/xiangyuecn/Recorder/blob/e1b50c0102d5fb3c7320bde4c9b398db200d2992/QuickStart.html#L23-L32

**Comment by yuenlin** [comment]
感谢解答，已解决。
