### ISSUE TITLE
求录音完成以后，转换Base64 代码

### ISSUE THREAD

**Issue by pangh-space** [xiangyuecn/Recorder#92]
![image](https://user-images.githubusercontent.com/11403496/86234389-67a66480-bbc9-11ea-8fd5-fdc7696f8974.png)

录音结束，点击上传方法中的代码，转换出来的Base64 有问题。中间有很多百分号（%）。有没有可以转换的方法？

**Comment by xiangyuecn** [comment]
decodeURIComponent
