### ISSUE TITLE
webm文件怎么转mp3

### ISSUE THREAD

**Issue by slientRain** [xiangyuecn/Recorder#94]

**Comment by xiangyuecn** [comment]
使用这个转换代码：
https://xiangyuecn.github.io/Recorder/assets/%E5%B7%A5%E5%85%B7-%E4%BB%A3%E7%A0%81%E8%BF%90%E8%A1%8C%E5%92%8C%E9%9D%99%E6%80%81%E5%88%86%E5%8F%91Runtime.html?jsname=lib.transform.mp32other

自己把webm blob传进去转换即可

**Comment by slientRain** [comment]
> 使用这个转换代码：
> https://xiangyuecn.github.io/Recorder/assets/%E5%B7%A5%E5%85%B7-%E4%BB%A3%E7%A0%81%E8%BF%90%E8%A1%8C%E5%92%8C%E9%9D%99%E6%80%81%E5%88%86%E5%8F%91Runtime.html?jsname=lib.transform.mp32other
> 
> 自己把webm blob传进去转换即可

搞定了，感谢大佬
