### ISSUE TITLE
IOS微信浏览器不支持录音功能

### ISSUE THREAD

**Issue by lixianghong66** [xiangyuecn/Recorder#96]
安卓微信浏览器可以支持
求解决方案

**Comment by xiangyuecn** [comment]
用特殊兼容版 RecordApp： https://github.com/xiangyuecn/Recorder/tree/master/app-support-sample

**Comment by lixianghong66** [comment]
> 
> 
> 用特殊兼容版 RecordApp： https://github.com/xiangyuecn/Recorder/tree/master/app-support-sample

我试过了，一样的结果，提示此浏览器不支持录音

**Comment by xiangyuecn** [comment]
UA发来看看😂

**Comment by lixianghong66** [comment]
> 
> 
> UA发来看看😂

Safari浏览器内核：Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1   （可行）

IOS微信浏览器内核：Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/7.0.14(0x17000e2b) NetType/WIFI Language/zh_CN   （不可行）

**Comment by lixianghong66** [comment]
> 
> 
> UA发来看看😂

帮忙看一下这个问题吧，谢谢了

**Comment by xiangyuecn** [comment]
没道理啊，提示“此浏览器不支持录音”是走的Recorder H5，默认是不能H5录音就优先走微信录音，能录音才会走Recorder H5啊

你是不是不是用的RecordApp测试地址 https://jiebian.life/web/h5/github/recordapp.aspx 测试的？

如果还有问题，把测试页面底下的 “浏览器环境情况 ”截图过来研究研究

**Comment by lixianghong66** [comment]
> 
> 
> 没道理啊，提示“此浏览器不支持录音”是走的Recorder H5，默认是不能H5录音就优先走微信录音，能录音才会走Recorder H5啊
> 
> 你是不是不是用的RecordApp测试地址 https://jiebian.life/web/h5/github/recordapp.aspx 测试的？
> 
> 如果还有问题，把测试页面底下的 “浏览器环境情况 ”截图过来研究研究

之前给的代码地址应该跟这个不一样吧

**Comment by xiangyuecn** [comment]
![image](https://user-images.githubusercontent.com/13175029/89750315-0ba2fa00-dafe-11ea-9a37-02bf8437a24e.png)
这个玩意特意加大加粗了😂
