### ISSUE TITLE
Runtime.Decode()方法如何替换

### ISSUE THREAD

**Issue by yaphetm** [xiangyuecn/Recorder#97]

**Comment by xiangyuecn** [comment]
DecodeAudio? copy 函数过去改改就行了

https://github.com/xiangyuecn/Recorder/blob/b6c2ed77e7269b96c2beae198a1be952374be99b/assets/%E5%B7%A5%E5%85%B7-%E4%BB%A3%E7%A0%81%E8%BF%90%E8%A1%8C%E5%92%8C%E9%9D%99%E6%80%81%E5%88%86%E5%8F%91Runtime.html#L293-L327
