### ISSUE TITLE
mp3格式文件生成频谱图

### ISSUE THREAD

**Issue by yaphetm** [xiangyuecn/Recorder#98]
怎样改变频谱图的输入源  直接从mp3文件读取  不使用麦克风

**Comment by xiangyuecn** [comment]
用AudioContext 解码MP3得到pcm，32位浮点数pcm转成Int16Array pcm，用定时器按照播放速率调用input输入pcm片段数据

**Comment by yaphetm** [comment]
有AudioContext的使用示例么？

**Comment by xiangyuecn** [comment]
https://github.com/xiangyuecn/Recorder/blob/master/assets/runtime-codes/fragment.playbuffer.js

**Comment by yaphetm** [comment]
wave.input(pcmData,powerLevel,sampleRate)   powerLevel参数怎么获得呢

**Comment by xiangyuecn** [comment]
https://github.com/xiangyuecn/Recorder/blob/b6c2ed77e7269b96c2beae198a1be952374be99b/src/recorder-core.js#L225-L247

**Comment by xiangyuecn** [comment]
现在已提供 BufferStreamPlayer 扩展，可以直接从音频文件播放并绘制可视化

https://github.com/xiangyuecn/Recorder/blob/ddd980e8e70715658519eee8d2fc8417b6fbca0c/README.md#L853-L920
